% Dark figure
set( gcf, ...
  'InvertHardcopy', 'off', ...
  'Color', 'k', ...
  'DefaultAxesColor', 'k', ...
  'DefaultAxesColorOrder', [ 1 1 1 ], ...
  'DefaultAxesXColor', 'w', ...
  'DefaultAxesYColor', 'w', ...
  'DefaultAxesZColor', 'w', ...
  'DefaultLineColor', 'w', ...
  'DefaultTextColor', 'w' )

