%------------------------------------------------------------------------------%
% DFNC - difference operators, node to cell

function df = dfnc( oper, f, x, dx, i, a, j, k, l )

switch oper

case 'h' % constant grid, flops: 1* 7+

dx = 0.25 * dx * dx;
switch a
case 1
  df = dx * ...
  ( f(j+1,k+1,l+1,i) - f(j,k,l,i) ...
  - f(j,k+1,l+1,i) + f(j+1,k,l,i) ...
  + f(j+1,k,l+1,i) - f(j,k+1,l,i) ...
  + f(j+1,k+1,l,i) - f(j,k,l+1,i) );
case 2
  df = dx * ...
  ( f(j+1,k+1,l+1,i) - f(j,k,l,i) ...
  + f(j,k+1,l+1,i) - f(j+1,k,l,i) ...
  - f(j+1,k,l+1,i) + f(j,k+1,l,i) ...
  + f(j+1,k+1,l,i) - f(j,k,l+1,i));
case 3
  df = dx * ...
  ( f(j+1,k+1,l+1,i) - f(j,k,l,i) ...
  + f(j,k+1,l+1,i) - f(j+1,k,l,i) ...
  + f(j+1,k,l+1,i) - f(j,k+1,l,i) ...
  - f(j+1,k+1,l,i) + f(j,k,l+1,i) );
otherwise error 'a'
end

case 'r' % rectangular grid, flops: 3* 9+

switch a
case 1
  df = 0.25 * ...
  ( ( x(j,k+1,l,2) - x(j,k,l,2) ) .* ...
    ( x(j,k,l+1,3) - x(j,k,l,3) ) .* ...
    ( f(j+1,k+1,l+1,i) - f(j,k,l,i)  ...
    - f(j,k+1,l+1,i) + f(j+1,k,l,i)  ...
    + f(j+1,k,l+1,i) - f(j,k+1,l,i)  ...
    + f(j+1,k+1,l  ,i) - f(j,k,l+1,i) ) );
case 2
  df = 0.25 * ...
  ( ( x(j,k,l+1,3) - x(j,k,l,3) ) .* ...
    ( x(j+1,k,l,1) - x(j,k,l,1) ) .* ...
    ( f(j+1,k+1,l+1,i) - f(j,k,l,i)  ...
    + f(j,k+1,l+1,i) - f(j+1,k,l,i)  ...
    - f(j+1,k,l+1,i) + f(j,k+1,l,i)  ...
    + f(j+1,k+1,l,i) - f(j,k,l+1,i) ) );
case 3
  df = 0.25 * ...
  ( ( x(j+1,k,l,1) - x(j,k,l,1) ) .* ...
    ( x(j,k+1,l,2) - x(j,k,l,2) ) .* ...
    ( f(j+1,k+1,l+1,i) - f(j,k,l,i)  ...
    + f(j,k+1,l+1,i) - f(j+1,k,l,i)  ...
    + f(j+1,k,l+1,i) - f(j,k+1,l,i)  ...
    - f(j+1,k+1,l,i) + f(j,k,l+1,i) ) );
otherwise error 'a'
end

case 'g' % general grid, flops: 57* 112+

b = mod( a, 3 ) + 1;
c = mod( a + 1, 3 ) + 1;
df = 1 / 12 * ...
(x(j+1,k+1,l+1,c).*((x(j+1,k,l,b)-x(j,k+1,l+1,b)).*(f(j+1,k,l+1,i)-f(j+1,k+1,l,i))+x(j,k+1,l+1,b).*(f(j,k+1,l,i)-f(j,k,l+1,i))...
      +(x(j,k+1,l,b)-x(j+1,k,l+1,b)).*(f(j+1,k+1,l,i)-f(j,k+1,l+1,i))+x(j+1,k,l+1,b).*(f(j,k,l+1,i)-f(j+1,k,l,i))...
      +(x(j,k,l+1,b)-x(j+1,k+1,l,b)).*(f(j,k+1,l+1,i)-f(j+1,k,l+1,i))+x(j+1,k+1,l,b).*(f(j+1,k,l,i)-f(j,k+1,l,i)))...
+x(j,k,l,c).*((x(j,k+1,l+1,b)-x(j+1,k,l,b)).*(f(j,k,l+1,i)-f(j,k+1,l,i))+x(j+1,k,l,b).*(f(j+1,k+1,l,i)-f(j+1,k,l+1,i))...
      +(x(j+1,k,l+1,b)-x(j,k+1,l,b)).*(f(j+1,k,l,i)-f(j,k,l+1,i))+x(j,k+1,l,b).*(f(j,k+1,l+1,i)-f(j+1,k+1,l,i))...
      +(x(j+1,k+1,l,b)-x(j,k,l+1,b)).*(f(j,k+1,l,i)-f(j+1,k,l,i))+x(j,k,l+1,b).*(f(j+1,k,l+1,i)-f(j,k+1,l+1,i)))...
+x(j,k+1,l+1,c).*((x(j,k,l,b)-x(j+1,k+1,l+1,b)).*(f(j,k+1,l,i)-f(j,k,l+1,i))+x(j+1,k+1,l+1,b).*(f(j+1,k,l+1,i)-f(j+1,k+1,l,i))...
      +(x(j+1,k,l+1,b)-x(j,k+1,l,b)).*(f(j,k,l+1,i)-f(j+1,k+1,l+1,i))+x(j,k+1,l,b).*(f(j+1,k+1,l,i)-f(j,k,l,i))...
      +(x(j+1,k+1,l,b)-x(j,k,l+1,b)).*(f(j+1,k+1,l+1,i)-f(j,k+1,l,i))+x(j,k,l+1,b).*(f(j,k,l,i)-f(j+1,k,l+1,i)))...
+x(j+1,k,l,c).*((x(j+1,k+1,l+1,b)-x(j,k,l,b)).*(f(j+1,k+1,l,i)-f(j+1,k,l+1,i))+x(j,k,l,b).*(f(j,k,l+1,i)-f(j,k+1,l,i))...
      +(x(j,k+1,l,b)-x(j+1,k,l+1,b)).*(f(j,k,l,i)-f(j+1,k+1,l,i))+x(j+1,k,l+1,b).*(f(j+1,k+1,l+1,i)-f(j,k,l+1,i))...
      +(x(j,k,l+1,b)-x(j+1,k+1,l,b)).*(f(j+1,k,l+1,i)-f(j,k,l,i))+x(j+1,k+1,l,b).*(f(j,k+1,l,i)-f(j+1,k+1,l+1,i)))...
+x(j+1,k,l+1,c).*((x(j,k,l,b)-x(j+1,k+1,l+1,b)).*(f(j,k,l+1,i)-f(j+1,k,l,i))+x(j+1,k+1,l+1,b).*(f(j+1,k+1,l,i)-f(j,k+1,l+1,i))...
      +(x(j,k+1,l+1,b)-x(j+1,k,l,b)).*(f(j+1,k+1,l+1,i)-f(j,k,l+1,i))+x(j+1,k,l,b).*(f(j,k,l,i)-f(j+1,k+1,l,i))...
      +(x(j+1,k+1,l,b)-x(j,k,l+1,b)).*(f(j+1,k,l,i)-f(j+1,k+1,l+1,i))+x(j,k,l+1,b).*(f(j,k+1,l+1,i)-f(j,k,l,i)))...
+x(j,k+1,l,c).*((x(j+1,k+1,l+1,b)-x(j,k,l,b)).*(f(j,k+1,l+1,i)-f(j+1,k+1,l,i))+x(j,k,l,b).*(f(j+1,k,l,i)-f(j,k,l+1,i))...
      +(x(j+1,k,l,b)-x(j,k+1,l+1,b)).*(f(j+1,k+1,l,i)-f(j,k,l,i))+x(j,k+1,l+1,b).*(f(j,k,l+1,i)-f(j+1,k+1,l+1,i))...
      +(x(j,k,l+1,b)-x(j+1,k+1,l,b)).*(f(j,k,l,i)-f(j,k+1,l+1,i))+x(j+1,k+1,l,b).*(f(j+1,k+1,l+1,i)-f(j+1,k,l,i)))...
+x(j+1,k+1,l,c).*((x(j,k,l,b)-x(j+1,k+1,l+1,b)).*(f(j+1,k,l,i)-f(j,k+1,l,i))+x(j+1,k+1,l+1,b).*(f(j,k+1,l+1,i)-f(j+1,k,l+1,i))...
      +(x(j,k+1,l+1,b)-x(j+1,k,l,b)).*(f(j,k+1,l,i)-f(j+1,k+1,l+1,i))+x(j+1,k,l,b).*(f(j+1,k,l+1,i)-f(j,k,l,i))...
      +(x(j+1,k,l+1,b)-x(j,k+1,l,b)).*(f(j+1,k+1,l+1,i)-f(j+1,k,l,i))+x(j,k+1,l,b).*(f(j,k,l,i)-f(j,k+1,l+1,i)))...
+x(j,k,l+1,c).*((x(j+1,k+1,l+1,b)-x(j,k,l,b)).*(f(j+1,k,l+1,i)-f(j,k+1,l+1,i))+x(j,k,l,b).*(f(j,k+1,l,i)-f(j+1,k,l,i))...
      +(x(j+1,k,l,b)-x(j,k+1,l+1,b)).*(f(j,k,l,i)-f(j+1,k,l+1,i))+x(j,k+1,l+1,b).*(f(j+1,k+1,l+1,i)-f(j,k+1,l,i))...
      +(x(j,k+1,l,b)-x(j+1,k,l+1,b)).*(f(j,k+1,l+1,i)-f(j,k,l,i))+x(j+1,k,l+1,b).*(f(j+1,k,l,i)-f(j+1,k+1,l+1,i))));

otherwise error 'oper'

end

