%------------------------------------------------------------------------------%
% Hourglass corrections, cell to node

function hg = hourglasscn( f, iq, j, k, l )

switch iq
case 1, hg = ...
  - f(j,k,l) - f(j-1,k-1,l-1) ...
  - f(j-1,k,l) - f(j,k-1,l-1) ...
  + f(j,k-1,l) + f(j-1,k,l-1) ...
  + f(j,k,l-1) + f(j-1,k-1,l);
case 2, hg = ...
  - f(j,k,l) - f(j-1,k-1,l-1) ...
  + f(j-1,k,l) + f(j,k-1,l-1) ...
  - f(j,k-1,l) - f(j-1,k,l-1) ...
  + f(j,k,l-1) + f(j-1,k-1,l);
case 3, hg = ...
  - f(j,k,l) - f(j-1,k-1,l-1) ...
  + f(j-1,k,l) + f(j,k-1,l-1) ...
  + f(j,k-1,l) + f(j-1,k,l-1) ...
  - f(j,k,l-1) - f(j-1,k-1,l);
case 4, hg = ...
  - f(j,k,l) + f(j-1,k-1,l-1) ...
  + f(j-1,k,l) - f(j,k-1,l-1) ...
  + f(j,k-1,l) - f(j-1,k,l-1) ...
  + f(j,k,l-1) - f(j-1,k-1,l);
otherwise error 'iq'
end

