meta
cd 'stats'
ft   = fopen( 't',        'w', endian );
fa   = fopen( 'amax',     'w', endian );
fa1  = fopen( 'amax1',    'w', endian );
fa2  = fopen( 'amax2',    'w', endian );
fa3  = fopen( 'amax3',    'w', endian );
fv   = fopen( 'vmax',     'w', endian );
fv1  = fopen( 'vmax1',    'w', endian );
fv2  = fopen( 'vmax2',    'w', endian );
fv3  = fopen( 'vmax3',    'w', endian );
fu   = fopen( 'umax',     'w', endian );
fu1  = fopen( 'umax1',    'w', endian );
fu2  = fopen( 'umax2',    'w', endian );
fu3  = fopen( 'umax3',    'w', endian );
fw   = fopen( 'wmax',     'w', endian );
fw1  = fopen( 'wmax1',    'w', endian );
fw2  = fopen( 'wmax2',    'w', endian );
fw3  = fopen( 'wmax3',    'w', endian );
fsa  = fopen( 'samax',    'w', endian );
fsa1 = fopen( 'samax1',   'w', endian );
fsa2 = fopen( 'samax2',   'w', endian );
fsa3 = fopen( 'samax3',   'w', endian );
fsv  = fopen( 'svmax',    'w', endian );
fsv1 = fopen( 'svmax1',   'w', endian );
fsv2 = fopen( 'svmax2',   'w', endian );
fsv3 = fopen( 'svmax3',   'w', endian );
fsu  = fopen( 'sumax',    'w', endian );
fsu1 = fopen( 'sumax1',   'w', endian );
fsu2 = fopen( 'sumax2',   'w', endian );
fsu3 = fopen( 'sumax3',   'w', endian );
ftn  = fopen( 'tnmax',    'w', endian );
ftn1 = fopen( 'tnmax1',   'w', endian );
ftn2 = fopen( 'tnmax2',   'w', endian );
ftn3 = fopen( 'tnmax3',   'w', endian );
fts  = fopen( 'tsmax',    'w', endian );
fts1 = fopen( 'tsmax1',   'w', endian );
fts2 = fopen( 'tsmax2',   'w', endian );
fts3 = fopen( 'tsmax3',   'w', endian );
fsl  = fopen( 'slmax',    'w', endian );
fsl1 = fopen( 'slmax1',   'w', endian );
fsl2 = fopen( 'slmax2',   'w', endian );
fsl3 = fopen( 'slmax3',   'w', endian );
far  = fopen( 'tarrmax',  'w', endian );
far1 = fopen( 'tarrmax1', 'w', endian );
far2 = fopen( 'tarrmax2', 'w', endian );
far3 = fopen( 'tarrmax3', 'w', endian );
fah  = fopen( 'tarrhypo', 'w', endian );
for it=1:nt
  file = sprintf( 'st%06d', it );
  eval( file )
  fwrite( ft,   t,           'float32' );
  fwrite( fa,   amax,        'float32' );
  fwrite( fa1,  amaxi(1),    'int32' );
  fwrite( fa2,  amaxi(2),    'int32' );
  fwrite( fa3,  amaxi(3),    'int32' );
  fwrite( fv,   vmax,        'float32' );
  fwrite( fv1,  vmaxi(1),    'int32' );
  fwrite( fv2,  vmaxi(2),    'int32' );
  fwrite( fv3,  vmaxi(3),    'int32' );
  fwrite( fu,   umax,        'float32' );
  fwrite( fu1,  umaxi(1),    'int32' );
  fwrite( fu2,  umaxi(2),    'int32' );
  fwrite( fu3,  umaxi(3),    'int32' );
  fwrite( fw,   wmax,        'float32' );
  fwrite( fw1,  wmaxi(1),    'int32' );
  fwrite( fw2,  wmaxi(2),    'int32' );
  fwrite( fw3,  wmaxi(3),    'int32' );
  fwrite( fsa,  samax,       'float32' );
  fwrite( fsa1, samaxi(1),   'int32' );
  fwrite( fsa2, samaxi(2),   'int32' );
  fwrite( fsa3, samaxi(3),   'int32' );
  fwrite( fsv,  svmax,       'float32' );
  fwrite( fsv1, svmaxi(1),   'int32' );
  fwrite( fsv2, svmaxi(2),   'int32' );
  fwrite( fsv3, svmaxi(3),   'int32' );
  fwrite( fsu,  sumax,       'float32' );
  fwrite( fsu1, sumaxi(1),   'int32' );
  fwrite( fsu2, sumaxi(2),   'int32' );
  fwrite( fsu3, sumaxi(3),   'int32' );
  fwrite( ftn,  tnmax,       'float32' );
  fwrite( ftn1, tnmaxi(1),   'int32' );
  fwrite( ftn2, tnmaxi(2),   'int32' );
  fwrite( ftn3, tnmaxi(3),   'int32' );
  fwrite( fts,  tsmax,       'float32' );
  fwrite( fts1, tsmaxi(1),   'int32' );
  fwrite( fts2, tsmaxi(2),   'int32' );
  fwrite( fts3, tsmaxi(3),   'int32' );
  fwrite( fsl,  slmax,       'float32' );
  fwrite( fsl1, slmaxi(1),   'int32' );
  fwrite( fsl2, slmaxi(2),   'int32' );
  fwrite( fsl3, slmaxi(3),   'int32' );
  fwrite( far,  tarrmax,     'float32' );
  fwrite( far1, tarrmaxi(1), 'int32' );
  fwrite( far2, tarrmaxi(2), 'int32' );
  fwrite( far3, tarrmaxi(3), 'int32' );
  fwrite( fah,  tarrhypo,    'float32' );
end
fclose( ft   );
fclose( fa   );
fclose( fa1  );
fclose( fa2  );
fclose( fa3  );
fclose( fv   );
fclose( fv1  );
fclose( fv2  );
fclose( fv3  );
fclose( fu   );
fclose( fu1  );
fclose( fu2  );
fclose( fu3  );
fclose( fw   );
fclose( fw1  );
fclose( fw2  );
fclose( fw3  );
fclose( fsa  );
fclose( fsa1 );
fclose( fsa2 );
fclose( fsa3 );
fclose( fsv  );
fclose( fsv1 );
fclose( fsv2 );
fclose( fsv3 );
fclose( fsu  );
fclose( fsu1 );
fclose( fsu2 );
fclose( fsu3 );
fclose( ftn  );
fclose( ftn1 );
fclose( ftn2 );
fclose( ftn3 );
fclose( fts  );
fclose( fts1 );
fclose( fts2 );
fclose( fts3 );
fclose( fsl  );
fclose( fsl1 );
fclose( fsl2 );
fclose( fsl3 );
fclose( far  );
fclose( far1 );
fclose( far2 );
fclose( far3 );
fclose( fah  );
cd '..'
