% Figure window

function tsfigure

figure

set( gcf, ...
  'Name', [ 'Time Series ' num2str(gcf) ], ...
  'NumberTitle', 'off', ...
  'KeyPressFcn', 'delete(gcbf)', ...
  'DefaultLineLinewidth', 2, ...
  'DefaultTextHorizontalAlignment', 'center' )

darkfig

