% Figure window

function tsfigure

figure

set( gcf, ...
  'Name', [ 'Time Series ' num2str(gcf) ], ...
  'NumberTitle', 'off', ...
  'KeyPressFcn', 'delete(gcbf)', ...
  'Color', 'k', ...
  'DefaultAxesColor', 'k', ...
  'DefaultAxesColorOrder', 'w', ...
  'DefaultAxesXColor', 'w', ...
  'DefaultAxesYColor', 'w', ...
  'DefaultAxesZColor', 'w', ...
  'DefaultLineColor', 'w', ...
  'DefaultLineLinewidth', 2, ...
  'DefaultTextHorizontalAlignment', 'center', ...
  'DefaultTextColor', 'w' )

