#!/bin/bash -e

mode=%(mode)s

cd "%(rundir)s"
if [ $( /bin/pwd | grep -v gpfs ) ]; then
    echo "Error: jobs must be run from /gpfs"
    exit
fi

echo "$( date ): %(code)s started" >> log
%(pre)s
case "$mode${1:--i}" in
    s-i)  time %(bin)s ;;
    s-g)  gdb %(bin)s ;;
    s-tv) totalview %(bin)s ;;
    p-i)  mpirun -machinefile mf -np %(np)s %(bin)s ;;
    p-tv) mpirun -tv -machinefile mf -np %(np)s %(bin)s ;;
esac
%(post)s
echo "$( date ): %(code)s finished" >> log

