#!/bin/bash

#PBS -N %(code)s%(count)s
#PBS -l walltime=%(walltime)s
#PBS -l nodes=%(nodes)s:ppn=%(ppn)s
#PBS -q dque
#PBS -M %(email)s
#PBS -m abe
#PBS -e stderr
#PBS -o stdout
#PBS -V

cd "%(rundir)s"

echo "$( date ): %(code)s started" >> log
%(pre)s
mpirun -machinefile $PBS_NODEFILE -np %(np)s %(bin)s
%(post)s
echo "$( date ): %(code)s finished" >> log

