#!/bin/bash -e

IFS=":$IFS"
tar=tar
for dir in $PATH; do [ -x $dir/gtar ] && tar=gtar; done
for dir in $PATH; do
for file in xlf95_r ifort pgf90 gfortran f95; do
  if [ -x $dir/$file ]; then
    sfc=$file
    break 2
  fi
done
done
IFS="${IFS:1}"

pfc='mpif90'
getarg=''
case $sfc in
xlf95_r)
  getarg='getarg.f'
  sfc='xlf95_r -q64 -qsuppress=cmpmsg -qfixed'
  pfc='mpxlf95_r -q64 -qsuppress=cmpmsg -qfixed'
  flags='-g -C -qflttrap -qsigtrap'
  flags='-O -C'
  flags='-O4'
  ;;
ifort)
  flags='-warn -CB -traceback'
  flags='-O -CB -traceback'
  flags='-O3'
  ;;
pgf90)
  getarg='getarg-pgf.f'
  sfc='pgf90'
  flags='-O -Ktrap=fp -Mbounds'
  flags='-O2'
  ;;
gfortran)
  flags='-Wall -O -g -pg'
  flags='-Wall -O -g -fbounds-check'
  flags='-Wall -O3'
  ;;
f95)
  flags='-g'
  flags=''
  if [ $( uname ) = SunOS ]; then
    getarg='getarg.f'
    flags='-g -w4 -u -C'
    flags='-w4 -O -C'
    flags='-w1 -O'
  fi
  ;;
*)
  echo "Error: no Fortran 95 compiler found"
  exit
esac

files="
  $getarg
  xsec.f
  newin.h
  scecvm4.f
  iobin.f
  iompi.f"

cd "$( dirname $0 )"
srcdir=$( /bin/pwd )
cd ..

mkdir -p tmp/scecvm
cd tmp/scecvm
for file in $files; do
  ln -s "$srcdir/$file" &> /dev/null || :
done
echo "$sfc $pfc $flags" > state
cat $files >> state

compile=yes
if [ -f state-vm ]; then
  compile=$( cmp state state-vm || : )
fi

if [ "$compile" ]; then
  echo "Compiling SCECVM"
  rm -f state-vm
  $tar xzf "$srcdir/../data/scecvm4.tgz"
  make="$sfc $flags xsec.f -o xsec"; echo $make; $make
  make="$sfc $flags $getarg iobin.f scecvm4.f -o scecvm4-s"; echo $make; $make
  make="$pfc $flags $getarg iompi.f scecvm4.f -o scecvm4-p"; echo $make; $make || :
  sed -n 's/.*ibig *= *\([0-9]*\).*/\1/p' newin.h > ibig
  rm -f *.o *.f *.h
  mv state state-vm
fi
rm -f $files

