%------------------------------------------------------------------------------%
% DCNG - cell-to-node general grid difference operator

function df = dcng( f, i, x, a, j, k, l )
b = mod( a,   3 ) + 1;
c = mod( a + 1, 3 ) + 1;
df = 1 / 12 * ...
(x(j+1,k,l,c).*((x(j,k+1,l,b)+x(j+1,k+1,l,b)).*(f(j,k,l-1,i)-f(j,k,l,i))+(x(j,k-1,l,b)+x(j+1,k-1,l,b)).*(f(j,k-1,l,i)-f(j,k-1,l-1,i))...
      +(x(j,k,l+1,b)+x(j+1,k,l+1,b)).*(f(j,k,l,i)-f(j,k-1,l,i))+(x(j,k,l-1,b)+x(j+1,k,l-1,b)).*(f(j,k-1,l-1,i)-f(j,k,l-1,i)))...
+x(j-1,k,l,c).*((x(j,k+1,l,b)+x(j-1,k+1,l,b)).*(f(j-1,k,l,i)-f(j-1,k,l-1,i))+(x(j,k-1,l,b)+x(j-1,k-1,l,b)).*(f(j-1,k-1,l-1,i)-f(j-1,k-1,l,i))...
      +(x(j,k,l+1,b)+x(j-1,k,l+1,b)).*(f(j-1,k-1,l,i)-f(j-1,k,l,i))+(x(j,k,l-1,b)+x(j-1,k,l-1,b)).*(f(j-1,k,l-1,i)-f(j-1,k-1,l-1,i)))...
+x(j,k+1,l,c).*((x(j+1,k,l,b)+x(j+1,k+1,l,b)).*(f(j,k,l,i)-f(j,k,l-1,i))+(x(j-1,k,l,b)+x(j-1,k+1,l,b)).*(f(j-1,k,l-1,i)-f(j-1,k,l,i))...
      +(x(j,k,l+1,b)+x(j,k+1,l+1,b)).*(f(j-1,k,l,i)-f(j,k,l,i))+(x(j,k,l-1,b)+x(j,k+1,l-1,b)).*(f(j,k,l-1,i)-f(j-1,k,l-1,i)))...
+x(j,k-1,l,c).*((x(j+1,k,l,b)+x(j+1,k-1,l,b)).*(f(j,k-1,l-1,i)-f(j,k-1,l,i))+(x(j-1,k,l,b)+x(j-1,k-1,l,b)).*(f(j-1,k-1,l,i)-f(j-1,k-1,l-1,i))...
      +(x(j,k,l+1,b)+x(j,k-1,l+1,b)).*(f(j,k-1,l,i)-f(j-1,k-1,l,i))+(x(j,k,l-1,b)+x(j,k-1,l-1,b)).*(f(j-1,k-1,l-1,i)-f(j,k-1,l-1,i)))...
+x(j,k,l+1,c).*((x(j+1,k,l,b)+x(j+1,k,l+1,b)).*(f(j,k-1,l,i)-f(j,k,l,i))+(x(j-1,k,l,b)+x(j-1,k,l+1,b)).*(f(j-1,k,l,i)-f(j-1,k-1,l,i))...
      +(x(j,k+1,l,b)+x(j,k+1,l+1,b)).*(f(j,k,l,i)-f(j-1,k,l,i))+(x(j,k-1,l,b)+x(j,k-1,l+1,b)).*(f(j-1,k-1,l,i)-f(j,k-1,l,i)))...
+x(j,k,l-1,c).*((x(j+1,k,l,b)+x(j+1,k,l-1,b)).*(f(j,k,l-1,i)-f(j,k-1,l-1,i))+(x(j-1,k,l,b)+x(j-1,k,l-1,b)).*(f(j-1,k-1,l-1,i)-f(j-1,k,l-1,i))...
      +(x(j,k+1,l,b)+x(j,k+1,l-1,b)).*(f(j-1,k,l-1,i)-f(j,k,l-1,i))+(x(j,k-1,l,b)+x(j,k-1,l-1,b)).*(f(j,k-1,l-1,i)-f(j-1,k-1,l-1,i)))...
 +x(j,k+1,l+1,c).*(x(j,k+1,l,b)-x(j,k,l+1,b)).*(f(j,k,l,i)-f(j-1,k,l,i))...
 +x(j,k-1,l-1,c).*(x(j,k-1,l,b)-x(j,k,l-1,b)).*(f(j,k-1,l-1,i)-f(j-1,k-1,l-1,i))...
 +x(j+1,k,l+1,c).*(x(j+1,k,l,b)-x(j,k,l+1,b)).*(f(j,k-1,l,i)-f(j,k,l,i))...
 +x(j-1,k,l-1,c).*(x(j-1,k,l,b)-x(j,k,l-1,b)).*(f(j-1,k-1,l-1,i)-f(j-1,k,l-1,i))...
 +x(j+1,k+1,l,c).*(x(j+1,k,l,b)-x(j,k+1,l,b)).*(f(j,k,l,i)-f(j,k,l-1,i))...
 +x(j-1,k-1,l,c).*(x(j-1,k,l,b)-x(j,k-1,l,b)).*(f(j-1,k-1,l,i)-f(j-1,k-1,l-1,i))...
 +x(j+1,k,l-1,c).*(x(j+1,k,l,b)-x(j,k,l-1,b)).*(f(j,k,l-1,i)-f(j,k-1,l-1,i))...
 +x(j-1,k,l+1,c).*(x(j-1,k,l,b)-x(j,k,l+1,b)).*(f(j-1,k,l,i)-f(j-1,k-1,l,i))...
 +x(j-1,k+1,l,c).*(x(j-1,k,l,b)-x(j,k+1,l,b)).*(f(j-1,k,l-1,i)-f(j-1,k,l,i))...
 +x(j+1,k-1,l,c).*(x(j+1,k,l,b)-x(j,k-1,l,b)).*(f(j,k-1,l-1,i)-f(j,k-1,l,i))...
 +x(j,k-1,l+1,c).*(x(j,k-1,l,b)-x(j,k,l+1,b)).*(f(j-1,k-1,l,i)-f(j,k-1,l,i))...
 +x(j,k+1,l-1,c).*(x(j,k+1,l,b)-x(j,k,l-1,b)).*(f(j-1,k,l-1,i)-f(j,k,l-1,i)));
%flops: 55* 344+

