%------------------------------------------------------------------------------%
% DFCN - difference operator, cell to node

function df = dfcn( operator, f, x, h, i, a, j, k, l )

switch operator

% constant grid, flops: 1* 7+
case 'h'
h = 0.25 * h * h;
switch a
case 1, df = h * ...
  ( f(j,k,l,i) - f(j-1,k-1,l-1,i) ...
  - f(j-1,k,l,i) + f(j,k-1,l-1,i) ...
  + f(j,k-1,l,i) - f(j-1,k,l-1,i) ...
  + f(j,k,l-1,i) - f(j-1,k-1,l,i) );
case 2, df = h * ...
  ( f(j,k,l,i) - f(j-1,k-1,l-1,i) ...
  + f(j-1,k,l,i) - f(j,k-1,l-1,i) ...
  - f(j,k-1,l,i) + f(j-1,k,l-1,i) ...
  + f(j,k,l-1,i) - f(j-1,k-1,l,i) );
case 3, df = h * ...
  ( f(j,k,l,i) - f(j-1,k-1,l-1,i) ...
  + f(j-1,k,l,i) - f(j,k-1,l-1,i) ...
  + f(j,k-1,l,i) - f(j-1,k,l-1,i) ...
  - f(j,k,l-1,i) + f(j-1,k-1,l,i) );
otherwise error a
end

% rectangular grid, flops: 7* 11+
case 'r'
switch a
case 1, df = 0.25 * ...
  ( ( x(j,k,l+1,3) - x(j,k,l,3) ) .* ...
  ( ( x(j,k+1,l,2) - x(j,k,l,2) ) .* ( f(j,k,l,i) - f(j-1,k,l,i) ) + ...
    ( x(j,k,l,2) - x(j,k-1,l,2) ) .* ( f(j,k-1,l,i) - f(j-1,k-1,l,i) ) ) ...
  + ( x(j,k,l,3) - x(j,k,l-1,3) ) .* ...
  ( ( x(j,k+1,l,2) - x(j,k,l,2) ) .* ( f(j,k,l-1,i) - f(j-1,k,l-1,i) ) + ...
    ( x(j,k,l,2) - x(j,k-1,l,2) ) .* ( f(j,k-1,l-1,i) - f(j-1,k-1,l-1,i) ) ) );
case 2, df = 0.25 * ...
  ( ( x(j+1,k,l,1) - x(j,k,l,1) ) .* ...
  ( ( x(j,k,l+1,3) - x(j,k,l,3) ) .* ( f(j,k,l,i) - f(j,k-1,l,i) ) + ...
    ( x(j,k,l,3) - x(j,k,l-1,3) ) .* ( f(j,k,l-1,i) - f(j,k-1,l-1,i) ) ) ...
  + ( x(j,k,l,1) - x(j-1,k,l,1) ) .* ...
  ( ( x(j,k,l+1,3) - x(j,k,l,3) ) .* ( f(j-1,k,l,i) - f(j-1,k-1,l,i) ) + ...
    ( x(j,k,l,3) - x(j,k,l-1,3) ) .* ( f(j-1,k,l-1,i) - f(j-1,k-1,l-1,i) ) ) );
case 3, df = 0.25 * ...
  ( ( x(j,k+1,l,2) - x(j,k,l,2) ) .* ...
  ( ( x(j+1,k,l,1) - x(j,k,l,1) ) .* ( f(j,k,l,i) - f(j,k,l-1,i) ) + ...
    ( x(j,k,l,1) - x(j-1,k,l,1) ) .* ( f(j-1,k,l,i) - f(j-1,k,l-1,i) ) ) ...
  + ( x(j,k,l,2) - x(j,k-1,l,2) ) .* ...
  ( ( x(j+1,k,l,1) - x(j,k,l,1) ) .* ( f(j,k-1,l,i) - f(j,k-1,l-1,i) ) + ...
    ( x(j,k,l,1) - x(j-1,k,l,1) ) .* ( f(j-1,k-1,l,i) - f(j-1,k-1,l-1,i) ) ) );
otherwise error a
end

% general grid, flops: 55* 90+
case 'g'
b = mod( a, 3 ) + 1;
c = mod( a + 1, 3 ) + 1;
df = 1 / 12 * ...
(x(j+1,k,l,c).*((x(j,k+1,l,b)+x(j+1,k+1,l,b)).*(f(j,k,l-1,i)-f(j,k,l,i)) ...
               +(x(j,k-1,l,b)+x(j+1,k-1,l,b)).*(f(j,k-1,l,i)-f(j,k-1,l-1,i)) ...
               +(x(j,k,l+1,b)+x(j+1,k,l+1,b)).*(f(j,k,l,i)-f(j,k-1,l,i)) ...
               +(x(j,k,l-1,b)+x(j+1,k,l-1,b)).*(f(j,k-1,l-1,i)-f(j,k,l-1,i))) ...
+x(j-1,k,l,c).*((x(j,k+1,l,b)+x(j-1,k+1,l,b)).*(f(j-1,k,l,i)-f(j-1,k,l-1,i)) ...
               +(x(j,k-1,l,b)+x(j-1,k-1,l,b)).*(f(j-1,k-1,l-1,i)-f(j-1,k-1,l,i)) ...
               +(x(j,k,l+1,b)+x(j-1,k,l+1,b)).*(f(j-1,k-1,l,i)-f(j-1,k,l,i)) ...
               +(x(j,k,l-1,b)+x(j-1,k,l-1,b)).*(f(j-1,k,l-1,i)-f(j-1,k-1,l-1,i))) ...
+x(j,k+1,l,c).*((x(j+1,k,l,b)+x(j+1,k+1,l,b)).*(f(j,k,l,i)-f(j,k,l-1,i)) ...
               +(x(j-1,k,l,b)+x(j-1,k+1,l,b)).*(f(j-1,k,l-1,i)-f(j-1,k,l,i)) ...
               +(x(j,k,l+1,b)+x(j,k+1,l+1,b)).*(f(j-1,k,l,i)-f(j,k,l,i)) ...
               +(x(j,k,l-1,b)+x(j,k+1,l-1,b)).*(f(j,k,l-1,i)-f(j-1,k,l-1,i))) ...
+x(j,k-1,l,c).*((x(j+1,k,l,b)+x(j+1,k-1,l,b)).*(f(j,k-1,l-1,i)-f(j,k-1,l,i)) ...
               +(x(j-1,k,l,b)+x(j-1,k-1,l,b)).*(f(j-1,k-1,l,i)-f(j-1,k-1,l-1,i)) ...
               +(x(j,k,l+1,b)+x(j,k-1,l+1,b)).*(f(j,k-1,l,i)-f(j-1,k-1,l,i)) ...
               +(x(j,k,l-1,b)+x(j,k-1,l-1,b)).*(f(j-1,k-1,l-1,i)-f(j,k-1,l-1,i))) ...
+x(j,k,l+1,c).*((x(j+1,k,l,b)+x(j+1,k,l+1,b)).*(f(j,k-1,l,i)-f(j,k,l,i)) ...
               +(x(j-1,k,l,b)+x(j-1,k,l+1,b)).*(f(j-1,k,l,i)-f(j-1,k-1,l,i)) ...
               +(x(j,k+1,l,b)+x(j,k+1,l+1,b)).*(f(j,k,l,i)-f(j-1,k,l,i)) ...
               +(x(j,k-1,l,b)+x(j,k-1,l+1,b)).*(f(j-1,k-1,l,i)-f(j,k-1,l,i))) ...
+x(j,k,l-1,c).*((x(j+1,k,l,b)+x(j+1,k,l-1,b)).*(f(j,k,l-1,i)-f(j,k-1,l-1,i)) ...
               +(x(j-1,k,l,b)+x(j-1,k,l-1,b)).*(f(j-1,k-1,l-1,i)-f(j-1,k,l-1,i)) ...
               +(x(j,k+1,l,b)+x(j,k+1,l-1,b)).*(f(j-1,k,l-1,i)-f(j,k,l-1,i)) ...
               +(x(j,k-1,l,b)+x(j,k-1,l-1,b)).*(f(j,k-1,l-1,i)-f(j-1,k-1,l-1,i))) ...
 +x(j,k+1,l+1,c).*(x(j,k+1,l,b)-x(j,k,l+1,b)).*(f(j,k,l,i)-f(j-1,k,l,i)) ...
 +x(j,k-1,l-1,c).*(x(j,k-1,l,b)-x(j,k,l-1,b)).*(f(j,k-1,l-1,i)-f(j-1,k-1,l-1,i)) ...
 +x(j+1,k,l+1,c).*(x(j+1,k,l,b)-x(j,k,l+1,b)).*(f(j,k-1,l,i)-f(j,k,l,i)) ...
 +x(j-1,k,l-1,c).*(x(j-1,k,l,b)-x(j,k,l-1,b)).*(f(j-1,k-1,l-1,i)-f(j-1,k,l-1,i)) ...
 +x(j+1,k+1,l,c).*(x(j+1,k,l,b)-x(j,k+1,l,b)).*(f(j,k,l,i)-f(j,k,l-1,i)) ...
 +x(j-1,k-1,l,c).*(x(j-1,k,l,b)-x(j,k-1,l,b)).*(f(j-1,k-1,l,i)-f(j-1,k-1,l-1,i)) ...
 +x(j+1,k,l-1,c).*(x(j+1,k,l,b)-x(j,k,l-1,b)).*(f(j,k,l-1,i)-f(j,k-1,l-1,i)) ...
 +x(j-1,k,l+1,c).*(x(j-1,k,l,b)-x(j,k,l+1,b)).*(f(j-1,k,l,i)-f(j-1,k-1,l,i)) ...
 +x(j-1,k+1,l,c).*(x(j-1,k,l,b)-x(j,k+1,l,b)).*(f(j-1,k,l-1,i)-f(j-1,k,l,i)) ...
 +x(j+1,k-1,l,c).*(x(j+1,k,l,b)-x(j,k-1,l,b)).*(f(j,k-1,l-1,i)-f(j,k-1,l,i)) ...
 +x(j,k-1,l+1,c).*(x(j,k-1,l,b)-x(j,k,l+1,b)).*(f(j-1,k-1,l,i)-f(j,k-1,l,i)) ...
 +x(j,k+1,l-1,c).*(x(j,k+1,l,b)-x(j,k,l-1,b)).*(f(j-1,k,l-1,i)-f(j,k,l-1,i)));

otherwise error operator

end
