%------------------------------------------------------------------------------%
% ISOSURFVIZ

for iz = 1:size( volumes, 1 )
  zone = volumes(iz,:);
  [ i1, i2 ] = zoneselect( zone, halo1, ncore, hypocenter, nrmdim );
  l = i1(3):i2(3);
  k = i1(2):i2(2);
  j = i1(1):i2(1);
  ng = i2 - i1 + 1;
  if sum( ng > 1 ) < 3, error( 'bad volume' ), end
  isoval = [ -isoval( [ 2 1 ] ) isoval ];
  alpha  = [  8  1  1  8 ] / 8;
  color  = [  0  1  1  1
             .5  1  1 .5
              1  1  1  0 ];
  switch field
  case 'v'
    if comp, vg =  v(j,k,l,comp); 
    else     vg = s1(j,k,l);
    end
  case 'w'
    if 3 < comp, vg = w2(j,k,l,comp-3); 
    elseif comp, vg = w1(j,k,l,comp); 
    else         vg = s2(j,k,l); 
    end
  end
  if comp, isoval = isoval .* isoval; end
  switch field
  case 'v'
    xg = x(j,k,l,:) + uscl * u(j,k,l,:); 
  case 'w'
    xg = 0.125 * ( ( ...
      x(j,k,l,:) + x(j+1,k+1,l+1,:) + ...
      x(j+1,k,l,:) + x(j,k+1,l+1,:) + ...
      x(j,k+1,l,:) + x(j+1,k,l+1,:) + ...
      x(j,k,l+1,:) + x(j+1,k+1,l,:) ) + ...
      uscl * ( ...
      u(j,k,l,:) + u(j+1,k+1,l+1,:) + ...
      u(j+1,k,l,:) + u(j,k+1,l+1,:) + ...
      u(j,k+1,l,:) + u(j+1,k,l+1,:) + ...
      u(j,k,l+1,:) + u(j+1,k+1,l,:) ) );
  end
  vg = permute( vg, [2 1 3] );
  xg = permute( xg, [2 1 3 4] );
  for i = 1:length( isoval );
    xg = isosurface( xg(:,:,:,1), xg(:,:,:,2), xg(:,:,:,3), ...
      sign( isoval(i) ) * vg, abs( isoval(i) ) );
    if ~isempty( xg.vertices )
      patch( xg, ...
        'FaceColor', color(:,i), ...
        'FaceAlpha', alpha(i), ...
        'FaceLighting', 'phong', ...
        'AmbientStrength',  .3, ...
        'DiffuseStrength',  .6, ...
        'SpecularStrength', .9, ...
        'BackFaceLighting', 'unlit', ...
        'Tag', 'isosurf', ...
        'EdgeColor', 'none' )
    end
  end
end 

