#!/bin/bash -e

account="phim.ucsd.edu"
account="moho.sdsu.edu"
account="altai.sdsu.edu"
account="ux451302@dslogin.sdsc.edu"

echo -e "\n$account"

ssh-add -L > /dev/null || ssh-add

files="
  README
  VERSION
  sord
  tarball
  remote
  sord.m
  defaults.m
  in.m
  infiles
  f
  m
"

rfiles=$( echo $files | sed 's|\([^ ]\+\)|sord/\1|g' )

case "$1" in
get) rsync -avub -e ssh --backup-dir=old $account:"$rfiles" . ;;
*)   rsync -avu  -e ssh --delete $files "$account:sord" ;;
esac

