#!/bin/bash -e

echo "Making SORD tarball"

files="
  sord/readme
  sord/defaults
  sord/in
  sord/fsord
  sord/msord
  sord/tarball
  sord/f
  sord/m
"

cd ..

tar zcf sord/sord.tgz $files

tag=$( date +%Y-%m-%d-%H-%M-%S )

cp sord/sord.tgz "sord/save/sord-$tag.tgz"

