#!/bin/bash -e

version=$( date +%Y-%m-%d-%H-%M-%S )

echo $version
echo $version > VERSION

files="
  README
  VERSION
  in
  in.*
  sord
  tarball
  f/
  m/
"

mkdir sord-$version

cp -al $files sord-$version

tar zcf sord-$version.tgz sord-$version

rm -rf sord-$version

