#!/bin/bash -e

dx=5000
[ -f tmp/dx ] && dx=$( cat tmp/dx )
echo -n "dx [$dx]: "
read i
[ -n "$i" ] && dx="$i"
cd util
./make
cd ../tmp
echo "$dx" > dx
./tsgrid
mv x1 x2 x3 th nn rlon rlat rdep data/

