#!/bin/bash -e

if mkdir tmp > /dev/null; then
  echo "setting up"
  cd tmp
  echo "1000." > dx
  echo "4000." > dx
  endian=$( perl -e 'print pack('V',1) eq pack('L',1) ? "l":"b"' )
  for file in ../ts/*; do
    ln -s "$file"
  done
  for file in ../data/*; do
    ln -s "$file"
  done
  tar zxf scecvm4.tgz
else
  cd tmp
fi

echo "compiling"
IFS=":$IFS"
for dir in $PATH; do
for file in xlf95_r ifort pgf90 gfortran f95; do
  if [ -x $dir/$file ]; then
    sfc=$file
    break 2
  fi
done
done

pfc='mpif90'
case $sfc in
xlf95_r)
  sfc='xlf95_r -qsuffix=f=f90 -q64 -qsuppress=cmpmsg'
  pfc='mpxlf95_r -qsuffix=f=f90 -q64 -qsuppress=cmpmsg'
  gflags='-p -g -C -qflttrap -qsigtrap -qlanglvl=95pure'
  oflags='-O5'
  ;;
ifort)
  gflags='-O0 -p -g -CB -warn -traceback -u'
  oflags='-O3'
  ;;
pgf90)
  gflags='-O0 -g -Ktrap=fp -Mbounds -Mdclchk -Mprof=lines'
  oflags='-fast'
  ;;
gfortran)
  gflags="-O0 -p -g -W -pedantic -std=legacy -fbounds-check"
  gflags="-O0 -g -fbounds-check -ffpe-trap=invalid,zero,overflow,underflow"
  oflags='-O3'
  ;;
f95)  gflags='-g'
  oflags='-O'
  if [ $( uname ) = SunOS ]; then
    gflags='-g -w4 -u -C'
    oflags='-fast'
  fi
  ;;
*)
  echo "Error: no Fortran 95 compiler found"
  exit
esac

flags=$oflags

$sfc $flags utm.f90 tscoords.f90 grid.f90 -o grid
rm -f *.mod

$sfc $flags iobin.f scecvm4.f -o scecvm
#$pfc $flags iompi.f scecvm4.f -o scecvm

echo "grid generation"
./grid

echo "velocity model extraction"
./scecvm

