"""
USC HPC - http://www.usc.edu/hpcc/

Add these to your .bashrc:
    source /usr/usc/globus/default/setup.sh
    export F77=gfortran
    export F90=gfortran
    source /usr/usc/mpich2/1.3.1..10/setup.sh

pbsnodes -a | grep main | sort | uniq -c
alias showme='qstat -u $USER"'

I/O to temporary space: /scratch
Use autogenerated sync.sh to check job during run.

The HPCC docs say: do not add to the front of your path.
Very inconvenient. I ignore this (at my peril).

Use /home instead of /auto
"""
login = 'hpc-login2.usc.edu'
hostname = 'hpc-login[12]'
rate = 1.1e6
queue = 'default'
queue_opts = [
    {'queue': 'default',  'maxnodes': 256, 'maxcores': 8, 'maxram': 11000, 'maxtime':  (24, 00)},
    {'queue': 'default',  'maxnodes': 256, 'maxcores': 4, 'maxram':  3500, 'maxtime':  (24, 00)},
    {'queue': 'largemem', 'maxnodes':   1, 'maxcores': 8, 'maxram': 63000, 'maxtime': (336, 00)},
    {'queue': 'nbns',     'maxnodes':  48, 'maxcores': 8, 'maxram': 11000, 'maxtime': (336, 00)},
]
launch = {
    's_exec':  '%(command)s',
    's_debug': 'gdb %(command)s',
    'submit':  'qsub "%(name)s.sh"',
    'submit2': 'qsub -W depend="afterok:%(depend)s" "%(name)s.sh"',
}

