#!/bin/bash -e

cat << END > $code-run
#!/bin/bash
cd "$rundir"
echo "\$( date ): Start $code" >> log
$pre
case "\${1:--i}" in
  -i) mpirun -machinefile mf -np $np $bin ;;
  -g) mpirun -machinefile mf -np $np -dbg=gdb $bin ;;
  -b) nohup mpirun -machinefile mf -np $np $bin > out.log & :; pid=\$! ;;
esac
cd "$rundir"
if [ "\$pid" ]; then
  echo "Background job started with PID \$pid" >> log
  echo "Background job started with PID \$pid"
else
  $post
fi
echo "\$( date ): Finish $code" >> log
END

cat << END > mf
node39:4
node40:4
node41:4
node42:4
node43:2
node44:2
node45:4
node46:2
node47:2
node48:2
node49:2
END

cat << END > $code-que
#!/bin/bash
echo "\$( date ): Job qued with ID: \$( qsub $code-script )" >> log
END

cat << END > $code-script
#!/bin/bash
#PBS -N $code-$count
#PBS -l nodes=$nodes:ppn=$ppn
#PBS -l walltime=$walltime
#PBS -q workq
#PBS -M $email
#PBS -m abe
#PBS -V
sleep 2
cd "$rundir"
echo "\$( date ): Start $code" >> log
$pre
mpiexec -n $np $bin
cd "$rundir"
$post
echo "\$( date ): Finish $code" >> log
END

chmod u+x $code-*

