#!/bin/bash -e

cat << END > run
#!/bin/bash
cd "$rundir"
echo "\$( date ): $code started" >> log
$pre
case "\${1:--i}" in
  -i) mpirun -machinefile mf -np $np $bin ;;
  -g) mpirun -machinefile mf -np $np -dbg=gdb $bin ;;
  -b) nohup mpirun -machinefile mf -np $np $bin > out.log & :; pid=\$! ;;
esac
if [ "\$pid" ]; then
  echo "$( date ): $code started with PID: \$pid" >> log
  echo "$code started with PID: \$pid"
else :
  $post
  echo "\$( date ): $code finished" >> log
fi
END

cat << END > mf
node39:4
node40:4
node41:4
node42:4
node43:2
node44:2
node45:4
node46:2
node47:2
node48:2
node49:2
END

cat << END > que
#!/bin/bash
cd "$rundir"
echo "\$( date ): $code qued with ID: \$( qsub script )" >> log
END

cat << END > script
#!/bin/bash
#PBS -N $code-$count
#PBS -l nodes=$nodes:ppn=$ppn
#PBS -l walltime=$walltime
#PBS -q workq
#PBS -M $email
#PBS -m abe
#PBS -V
sleep 2
cd "$rundir"
echo "\$( date ): $code started" >> log
$pre
mpiexec -n $np $bin
$post
echo "\$( date ): $code finished" >> log
END

chmod u+x run que script

