#!/bin/bash -e

runs="r4 r3 r2 r1"
runs="r5 r6 r7 r8"
runs="r4 r3 r2"
runs="r5 r6 r7"

rm -f timing
for run in $runs; do
  np=$( awk '/ np / { print $4 * $5 * $6 }' $run/meta.m )
  timing=$( awk '/step/ { print $1 }' $run/log )
  echo $np $timing >> timing
done

