#!/bin/bash -e

files="
  readme
  sord
  defaults.m
  in.m
  in
  sh
  f
  m
  viz
"

rfiles=$( echo $files | sed 's|\([^ ]\+\)|/media/usbdisk/sord/\1|g' )

case "$1" in
get) rsync -avub -e ssh --backup-dir=old "$rfiles" . ;;
*)   rsync -avL  -e ssh --delete $files "/media/usbdisk/sord/" ;;
esac

