#!/bin/bash -e
# Put all your machine specific configuration in here

IFS=":$IFS"

tar="tar"
for dir in $PATH; do
  if [ -x "$dir/gtar" ]; then tar="gtar"; break; fi
done

for dir in $PATH; do
for file in xlf95_r ifort pgf90 gfortran f95; do
  if [ -x "$dir/$file" ]; then sfc="$file"; break 2; fi
done
done

IFS="${IFS:1}"

scc='cc'
pcc='mpicc'
pfc='mpif90'
getarg=''
case $sfc in
xlf95_r)
  timer="hpmcount -nao prof/hpm"
  sfc='xlf95_r -u -q64 -qsuppress=cmpmsg -qlanglvl=2003pure -qsuffix=f=f90'
  pfc='mpxlf95_r -u -q64 -qsuppress=cmpmsg -qlanglvl=2003pure -qsuffix=f=f90'
  gflags='-g -p -C -qflttrap -qsigtrap'
  gflags='-g -O0 -C -qflttrap -qsigtrap'
  oflags='-O -C -qflttrap -qsigtrap'
  oflags='-O4' # -O3 is MUCH slower
  ;;
ifort)
  sfc='ifort -u -std95 -warn'
  pfc='mpif90 -u -std95 -warn'
  gflags='-g -p -CB -traceback'
  gflags='-g -O0 -CB -traceback'
  oflags='-O -override_limits -CB -traceback'
  oflags='-O3 -override_limits'
  oflags='-O3'
  ;;
pgf90)
  getarg='getarg-pgf.f90'
  gflags='-g -Ktrap=fp -Mbounds -Mdclchk -Mprof=func -Mprof=lines'
  gflags='-g -Ktrap=fp -Mbounds -Mdclchk -Mprof=func'
  gflags='-g -O0 -Ktrap=fp -Mbounds -Mdclchk'
  oflags='-fast -Ktrap=fp -Mbounds -Mdclchk'
  oflags='-fast -Mprof=func'
  oflags='-fast'
  ;;
gfortran)
  sfc='gfortran -fimplicit-none -Wall -std=f95 -pedantic'
  sfc='gfortran -fimplicit-none -Wall -pg'
  sfc='gfortran -fimplicit-none -Wall'
  pfc='mpif90 -fimplicit-none -Wall -std=f95 -pedantic'
  pfc='mpif90 -fimplicit-none -Wall -mpe=mpilog'
  pfc='mpif90 -fimplicit-none -Wall'
  gflags='-g -pg -fbounds-check -ffpe-trap=invalid,zero,overflow'
  gflags=''
  gflags='-g -fbounds-check -ffpe-trap=invalid,zero,overflow'
  oflags='-O -fbounds-check -ffpe-trap=invalid,zero,overflow'
  oflags='-O3 -fbounds-check -ffpe-trap=invalid,zero,overflow'
  oflags='-O'
  oflags='-O3'
  ;;
f95)
  gflags='-g'
  oflags='-O'
  if [ $( uname ) = SunOS ]; then
    getarg='getarg.f90'
    gflags='-w4 -u -C -g'
    oflags='-w4 -u -fast -C'
    oflags='-w4 -u -fast'
  fi
  ;;
*)
  echo "Error: no Fortran 95 compiler found"
  exit 1
esac

# Host
if [ "$machine" ]; then :
elif [ "$HOSTNAME" = 'cluster.geo.berkeley.edu' ]; then machine=calgeo
elif [ "$HOSTNAME" = master ];   then machine=babieca
elif [ "$HOSTNAME" = ds011 ];    then machine=datastar32
elif [ "${HOSTNAME:0:2}" = ds ]; then machine=datastar
elif [ "${HOSTNAME:0:2}" = tg ]; then machine=tgsdsc
else machine=${HOSTNAME%%.*}
fi

# Machine attributes
maxnodes=1; maxcpus=1; maxram=800; maxmm=0; rate=500
case $machine in
  wide)                     maxcpus=2;  maxram=3800 ;;
  kim)                      maxcpus=2;  maxram=800  ;;
  phim)                                 maxram=2800;   rate=400 ;;
  altai)                    maxcpus=8;  maxram=30000;  rate=100 ;;
  calgeo)     maxnodes=16;  maxcpus=4;  maxram=1500 ;;
  babieca)    maxnodes=32;  maxcpus=2;  maxram=1800;   rate=100 ;;
  tgsdsc)     maxnodes=256; maxcpus=2;  maxram=3000;   rate=1000; maxmm=1080 ;;
  datastar)   maxnodes=265; maxcpus=8;  maxram=13500;  rate=500;  maxmm=1080 ;;
  datastar32) maxnodes=5;   maxcpus=32; maxram=124000; rate=500;  maxmm=1080 ;;
  intensity)  sfc='gfortran'; oflags='-O3'; gflags='-g' ;;
esac

