#!/bin/bash -e

IFS=":$IFS"
for dir in $PATH; do
for file in xlf95_r ifort pgf90 gfortran f95; do
  if [ -x $dir/$file ]; then
    sfc=$file
    break 2
  fi
done
done
IFS="${IFS:1}"

pfc='mpif90'
getarg=''
case $sfc in
xlf95_r)
  sfc='xlf95_r -q64 -qsuppress=cmpmsg -qlanglvl=95pure -qsuffix=f=f90'
  pfc='mpxlf95_r -q64 -qsuppress=cmpmsg -qlanglvl=95pure -qsuffix=f=f90'
  gflags='-g -p -C -qflttrap -qsigtrap'
  gflags='-g -O0 -C -qflttrap -qsigtrap'
  oflags='-O -C -qflttrap -qsigtrap'
  oflags='-O5'
  ;;
ifort)
  sfc='ifort -implicitnone -std95 -warn'
  pfc='mpif90 -implicitnone -std95 -warn'
  gflags='-g -p -CB -traceback'
  gflags='-g -O0 -CB -traceback'
  oflags='-O -override_limits -CB -traceback'
  oflags='-O3 -override_limits'
  ;;
pgf90)
  getarg='getarg-pgf.f90'
  gflags='-g -Ktrap=fp -Mbounds -Mdclchk -Mprof=func -Mprof=lines'
  gflags='-g -Ktrap=fp -Mbounds -Mdclchk -Mprof=func'
  gflags='-g -O0 -Ktrap=fp -Mbounds -Mdclchk'
  oflags='-fast -Ktrap=fp -Mbounds -Mdclchk'
  oflags='-fast'
  ;;
gfortran)
  sfc='gfortran -fimplicit-none -Wall -std=f95 -pedantic'
  sfc='gfortran -fimplicit-none -Wall'
  pfc='mpif90 -fimplicit-none -Wall'
  gflags='-g -pg -fbounds-check -ffpe-trap=invalid,zero,overflow'
  gflags='-g -fbounds-check -ffpe-trap=invalid,zero,overflow'
  oflags='-O -fbounds-check -ffpe-trap=invalid,zero,overflow'
  oflags='-O3 -fbounds-check -ffpe-trap=invalid,zero,overflow'
  oflags='-O3'
  ;;
f95)
  gflags='-g'
  oflags='-O'
  if [ $( uname ) = SunOS ]; then
    getarg='getarg.f90'
    gflags='-w4 -u -C -g'
    oflags='-w4 -u -fast -C'
    oflags='-w4 -u -fast'
  fi
  ;;
*)
  echo "Error: no Fortran 95 compiler found"
  exit 1
esac

