#!/bin/bash -e
# Default run scripts

cat << END > run
#!/bin/bash -e
mode=$mode
cd "$rundir"
if [ "\$mode" = p ] && mpich2version &> /dev/null && ! mpdtrace &> /dev/null; then
  if [ ! -e $HOME/.mpd.conf ]; then
    c=( a b c d e f g h i j k l m n o p q r s t u v w x y z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z 0 1 2 3 4 5 6 7 8 9 ! @ \# $ % ^ \& )
    n=\${#c[@]}
    for (( i=1; i<=16; i++ )); do pw="\$pw\${c[\$RANDOM%n]}"; done
    echo "secretword=\$pw" > $HOME/.mpd.conf
    chmod 600 $HOME/.mpd.conf
  fi
  mpd --daemon
fi
echo "\$(date): $code started" >> log
$pre
case "\$mode\${1:--i}" in
  s-i)   time $bin ;;
  s-g)   gdb $bin ;;
  s-ddd) ddd $bin ;;
  p-i)   mpiexec -np $np time $bin ;;
  p-g)   mpiexec -gdb -np $np $bin ;;
  p-ddd) mpiexec -np $np ddd $bin ;;
esac
$post
echo "\$(date): $code finished" >> log
END

cat << END > que
#!/bin/bash -e
cd "$rundir"
if [ "\$mode" = p ] && mpich2version &> /dev/null && ! mpdtrace &> /dev/null; then
  if [ ! -e $HOME/.mpd.conf ]; then
    c=( a b c d e f g h i j k l m n o p q r s t u v w x y z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z 0 1 2 3 4 5 6 7 8 9 ! @ \# $ % ^ \& )
    n=\${#c[@]}
    for (( i=1; i<=16; i++ )); do pw="\$pw\${c[$RANDOM%n]}"; done
    echo "secretword=\$pw" > $HOME/.mpd.conf
    chmod 600 $HOME/.mpd.conf
  fi
  mpd --daemon
fi
nice nohup ./run > out.log &
pid=\$!
echo "\$(date): PID: \$pid" >> log
echo "$code started with PID: \$pid"
END

chmod u+x run que

