#!/bin/bash -e

cat << END > run
#!/bin/bash -e
cd "$rundir"
echo "\$(date): $code started" >> log
$pre
[ "$mode" = p ] && mpich2version &> /dev/null && ! mpdtrace &> /dev/null && mpd --daemon
case "\${1:--i}$mode" in
  -is) $bin ;;
  -gs) ddd $bin ;;
  -bs) nice nohup $bin > out.log & :; pid=\$! ;;
  -ip) mpiexec -l -np $np $bin ;;
  -gp) mpiexec -l -gdb -np $np $bin ;;
  -dddp) mpiexec -l -np $np ddd $bin ;;
  -bp) nice nohup mpiexec -l -np $np $bin > out.log & :; pid=\$! ;;
esac
if [ "\$pid" ]; then
  echo "\$(date): $code started with PID: \$pid" >> log
  echo "$code started with PID: \$pid"
else :
  $post
  echo "\$(date): $code finished" >> log
fi
END

chmod u+x run

