#!/bin/bash -e

# Prepare input file

mkdir -p tmp
cat $@ | sed "
s/#.*$//;
s/;/\\
/g;
" | sed "
s/[][,{}='	]/ /g;
s/  */ /g;
s/^ //;
s/ $//;
/^$/d
" > tmp/input

# join lines
# " | sed -e :a -e "
# /\\ *$/N;
# s/\\ *\n//;
# ta

# Read input
while read key params; do
set -- $params
case "$key" in
    nt) nt=$1 ;;
    nn) nm3=( $1 $2 $3 ) ;;
    np) np3=( $1 $2 $3 ) ;;
    dx) dx=$1 ;;
    npml) npml=$1 ;;
    oplevel) oplevel=$1 ;;
    datadir) datadir="$1" ;;
    faultnormal) faultnormal=$1 ;;
    return) break ;;
esac
done < tmp/input

