#!/bin/bash -e

if [ "${HOSTNAME:0:2}" = tg ]; then machine=teragrid
elif [ "$HOSTNAME" = master ]; then machine=babieca
fi

case "$machine$1" in
babieca)   hosts="node%d"; i1=1;   i2=36  ;;
babieca-i) hosts="node%d"; i1=37;  i2=48  ;;
teragrid)  hosts="tg-c%d"; i1=127; i2=130 ;;
*) exit ;;
esac

for (( i=$i1; i<=$i2; i=i+1 )); do
  host=$( echo $hosts $i | awk '{ printf $1, $2 }' )
  load=$( ssh $host "cut -f1 -d\  /proc/loadavg" )
  echo "$host $load"
done

