#!/bin/bash -e

make="$*"
files="${make//* -o/}"

while getopts o: opt; do
case "$opt" in
  o) obj="$OPTARG" ;;
esac
done
echo $obj

echo "$files"
exit

echo $make > state
cat $* >> state

compile=yes
if [ -f state-$object ]; then
  compile=$( cmp state state-$object || : )
fi

if [ "$compile" ]; then
  rm -f state-$object
  echo $make
  $make
  mv state state-$object
  rm -f *.o *.mod *.ipo *.il *.stb
fi 

