#!/bin/bash -e

make="$1"
srcdir="${2:-.}"
src="${make##* -o }"
obj="${src%% *}"
src="${src#* }"

if [ "$src" = "$make" -o "$obj" = "$src" -o -z "$obj" -o -z "$src" -o -z "$srcdir" ]; then
  echo Error
  exit 1
fi 

echo "$make" > state
for file in $src do
  ln -s "$srcdir/$file" &> /dev/null || :
  cat "$file" >> state
done

compile=yes
if [ -f $obj.state ]; then
  compile=$( diff state $obj.state || : )
  [ "$compile" ] && echo "$compile"
fi

if [ "$compile" ]; then
  rm -f $obj.state
  echo $make
  $make
  mv state $obj.state
  rm -f $src *.o *.mod *.ipo *.il *.stb
fi 

