#!/bin/bash -e

[ -x sord ]

cat << END > 'in.m'
  np = [ 1 1 1 ];
  faultnormal = 0;
  rsource = 150.;
  nt = 400;
  nn = [ 81 81 81 ];
  bc1 = [ 1 1 1 ];
  bc2 = [ 1 1 1 ];
  out = { 'x' 1   21 21 61   61 61 61 };
  out = { 'v' 1   21 21 61   61 61 61 };
  out = { 'v' 20  1 1 1   -1 -1 -1 };
END
./sord -d
mv out runs/pmltest1

cat << END >> 'in.m'
  np = [ 1 1 1 ];
  faultnormal = 0;
  rsource = 150.;
  nt = 400;
  nn = [ 161 161 161 ];
  bc1 = [ 0 0 0 ];
  bc2 = [ 0 0 0 ];
  out = { 'x' 1   61 61 101   101 101 101 };
  out = { 'v' 1   61 61 101   101 101 101 };
  out = { 'v' 20  1 1 1   -1 -1 -1 };
END
./sord
mv out runs/pmltest2

