#!/bin/bash -e
# SORD remote install & execution

acct="${1:?}"

# Install files
files="\
  email
  doc
  sord
  in.m
  in
  sh
  g
  f
  m
  util
  cvm
  data"
files=$( echo $files )
ssh="ssh ${acct//,/ ssh }"
target="${ssh##* }"
ssh="${ssh% *}"
echo "rsync -av --delete -e \"$ssh\" $files $target:sord"
rsync -av --delete -e "$ssh" $files $target:sord 

# Execute command
[ -z "$2" ] && exit 0
shift 1
cmd="cd sord; $*"
ssh="ssh -tX ${acct//,/ ssh -tX }"
echo "$ssh bash --login -c \"$cmd\""
$ssh "bash --login -c \"$cmd\""

