#!/bin/bash -e

dir=$( /bin/pwd )
base=$( basename "$dir" )
version=$( date +%Y%m%d%H%M%S )

s=""
g=""
while getopts sg opt; do eval "$opt=y"; done

cat << END > versionmeta.m
version = '$version';
login   = '$LOGNAME';
name    = '$( finger $LOGNAME | sed -n 's/^Login.*:.*e: //p' )';
host    = '$HOSTNAME';
dir     = '$dir';
END

files="
  $base/versionmeta.m
  $base/doc
  $base/sord
  $base/in.m
  $base/in
  $base/sh
  $base/f
  $base/m
  $base/util
  $base/cvm
"
mkdir -p tmp
cd $( dirname "$dir" )
tar cf - $files | gzip > "$dir/tmp/$base.tgz"
cd "$dir"

mkdir -p save/good
[ "$g" -o "$s" ] && cp "tmp/$base.tgz" "save/$base-$version.tgz"
[ "$g" ]         && cp "tmp/$base.tgz" "save/good/$base-$version.tgz"

exit 0

