#!/bin/bash -e

version=$( date +%Y-%m-%d-%H-%M-%S )
base=sord-$version

cat << END > versionmeta.m
version = '$version';
login   = '$LOGNAME';
name    = '$( finger $LOGNAME | sed -n 's/^.*e: //p' )';
host    = '$HOSTNAME';
dir     = '$( /bin/pwd )';
END

files="
  $base/versionmeta.m
  $base/readme
  $base/sord
  $base/defaults.m
  $base/in.m
  $base/in
  $base/sh
  $base/f
  $base/m
"

ln -s . $base
rm -f f/*.o f/*.mod f/*.ipo f/*.il f/*.stb
mkdir -p tmp
tar cf - $files | gzip > tmp/sord.tgz
rm $base

if [ "x$1" = "x-s" ]; then
  cp tmp/sord.tgz save/$base.tgz
fi

