#!/bin/bash -e

version=$( date +%Y-%m-%d-%H-%M-%S )
date=$( date )

echo $version

cat << END > version.m
version = '$version';
date    = '$date';
host    = '$HOSTNAME';
dir     = '$( /bin/pwd )';
os      = '$( uname -a )';
login   = '$LOGNAME';
name    = '$( finger $LOGNAME | sed -n 's/^.*e: //p' )';
END

ln -s . $version

files="
  $version/version.m
  $version/readme
  $version/sord
  $version/defaults.m
  $version/in.m
  $version/in
  $version/sh
  $version/f
  $version/m
"

rm -f f/*.o f/*.mod f/*.ipo

tar cf - $files | gzip > sord.tgz

rm $version

if [ "x$1" = "x-s" ]; then
  cp sord.tgz save/sord-$version.tgz
fi

