#!/bin/bash -e

if [ $( /bin/pwd | grep -v gpfs ) ]; then
  echo "Error: jobs must be run from /gpfs"
  exit
fi

cat << END > run
#!/bin/bash -e
if ! grep -q "\$HOSTNAME" mf; then
  echo "Error: interactive jobs must be launched from the following hosts:"
  sed 's/^/  /; s/:2//' mf
  exit
fi
echo "\$(date): Start SORD run" >> log
END

case "$mode" in
s) cat << END >> run
case \${1:?} in
  -i) ./sord-s ;;
  -g) totalview ./sord-s ;;
  -b) nohup ./sord-s > out.log & :; pid=\$!
      echo "Background job started with PID \$pid" >> log
      echo "Background job started with PID \$pid" ;;
esac
echo "\$(date): Finished!" >> log
END
;;
p) cat << END >> run
case \${1:?} in
  -i) mpirun -machinefile mf -np $np ./sord-p ;;
  -g) mpirun -tv -machinefile mf -np $np ./sord-p ;;
  -b) nohup mpirun -machinefile mf -np $np ./sord-p > out.log & :; pid=\$!
      echo "Background job started with PID \$pid" >> log
      echo "Background job started with PID \$pid" ;;
esac
echo "\$(date): Finished!" >> log
END
;;
esac

cat << END > mf
tg-c127:2
tg-c128:2
tg-c129:2
tg-c130:2
END

cat << END > que
#!/bin/bash
qsub pbsscript >> log
END

cat << END > pbsscript
#!/bin/bash
#PBS -N sord-$count
#PBS -l walltime=$walltime
#PBS -l nodes=$nodes:ppn=$ppn
#PBS -q dque
#PBS -M $email
#PBS -m abe
#PBS -V
cd "$rundir"
echo "\$PBS_JOBID" >> log
echo "\$(date): Start SORD run" >> log
mpirun -machinefile \$PBS_NODEFILE -np $np ./sord-$mode
echo "\$(date): Finished!" >> log
END

chmod u+x run que pbsscript

if [ "$nc" ]; then

cat << END > que-vm
#!/bin/bash
qsub pbsscript-vm >> log
END

cat << END > pbsscript-vm
#!/bin/bash
#PBS -N sord-vm-$count
#PBS -l walltime=$walltime
#PBS -l nodes=$nodes:ppn=$ppn
#PBS -q dque
#PBS -M $email
#PBS -m abe
#PBS -V
cd "$rundir"
echo "\$PBS_JOBID" >> log
echo "\$(date): Start VM run" >> log
cd "$rundir/vm"
mpirun -machinefile \$PBS_NODEFILE -np $np ./scecvm4-$mode $nc rlon rlat rdep rho vp vs
mv rho vp vs "$rundir/data"
cd "$rundir"
echo "\$(date): Start SORD run" >> log
mpirun -machinefile \$PBS_NODEFILE -np $np ./sord-$mode
echo "\$(date): Finished!" >> log
END

chmod u+x que-vm pbsscript-vm

fi

