#!/bin/bash -e

[ -x sord ]
mkdir -p tmp/vm
./sord
srcdir=$( /bin/pwd )
cd util
./make
cd "$srcdir/tmp"
./tsgrid
mv th x1 x2 x3 nn rlon rlat rdep meta.m vm/
if [ nn=$( cat vm/nn ) -gt 4000000 ]; then
  echo "Deferring velocity model generation"
else
  cd vm
  ./scecvm4-s
fi

