#!/bin/bash -e
trap 'echo ERROR in terashake script $_' ERR

if [ -d /gpfs ]; then
  mkdir -p /gpfs/$LOGNAME/sord/tmp
  mkdir -p /gpfs/$LOGNAME/sord/out
  ln -sf /gpfs/$LOGNAME/sord/tmp
  ln -sf /gpfs/$LOGNAME/sord/out
fi
./sord -n
srcdir=$( /bin/pwd )
cd util
[ tsgrid.f90 -nt "$srcdir/tmp/tsgrid" ] && ./make
cd "$srcdir/tmp"
./tsgrid
rm -rf data vm
mkdir data
mv ts1 x1 x2 x3 meta.m data/
cp -r scecvm vm
mv rlon rlat rdep vm/
nc=$( cat nc )
if [ "$nc" -gt 4000000 ]; then
  echo "Deferring velocity model generation"
  cd "$srcdir"
  ./sord
  count=$( cat tmp/count )
  mv tmp/data tmp/vm "out/$count/"
else
  cd vm
  ./scecvm4-s $nc rlon rlat rdep rho vp vs
  mv rho vp vs "$srcdir/tmp/data/"
fi

