#!/bin/bash -e

./sord
srcdir=$( /bin/pwd )
cd util
[ tsgrid.f90 -nt "$srcdir/tmp/tsgrid" ] && ./make
cd "$srcdir/tmp"
rm -rf data vm
mkdir data
cp -r scecvm vm
./tsgrid
nn=$( cat nn )
mv th x1 x2 x3 meta.m data/
mv nn rlon rlat rdep vm/
if [ "$nn" -gt 4000000 ]; then
  echo "Deferring velocity model generation"
  count=$( cat count )
  mv data "$srcdir/out/$count/"
  mv vm "$srcdir/out/$count/"
else
  cd vm
  ./scecvm4-s
  mv rho vp vs "$srcdir/tmp/data/"
fi

