#!/bin/bash -e


files="
  sord/readme
  sord/fortran/*.f95
  sord/fortran/sord
  sord/fortran/tarball
  sord/fortran/in
  sord/fortran/defaults
  sord/matlab/*.m
  sord/matlab/sord
  sord/matlab/tarball
  sord/matlab/batchjob"

cd ../..

tar zcvf sord/sord.tgz $files

tag=$( date +%Y-%m-%d-%H-%M-%S )

cp sord/sord.tgz "sord/save/sord-$tag.tgz"

