#!/bin/bash -e

mode=%(mode)s

cd "%(rundir)s"
./mpd

echo "$( date ): %(code)s started" >> log
%(pre)s
case "$mode${1:--i}" in
    s-i)   time %(bin)s ;;
    s-g)   gdb  %(bin)s ;;
    s-ddd) ddd  %(bin)s ;;
    p-i)   mpiexec -np %(np)s time %(bin)s ;;
    p-g)   mpiexec -np %(np)s -gdb %(bin)s ;;
    p-ddd) mpiexec -np %(np)s ddd  %(bin)s ;;
esac
%(post)s
echo "$( date ): %(code)s finished"

