#!/bin/bash -e

#@environment = COPY_ALL;\\
#AIXTHREAD_SCOPE=S;\\
#MP_ADAPTER_USE=dedicated;\\
#MP_CPU_USE=unique;\\
#MP_CSS_INTERRUPT=no;\\
#MP_EAGER_LIMIT=16384;\\
#MP_EUIDEVELOP=min;\\
#MP_LABELIO=yes;\\
#MP_POLLING_INTERVAL=100000;\\
#MP_PULSE=0;\\
#MP_SHARED_MEMORY=yes;\\
#MP_SINGLE_THREAD=no;\\
#RT_GRQ=ON;\\
#XLSMPOPTS="stack=67108864"
#@ job_name = %(code)s%(count)s
#@ initialdir = %(rundir)s
#@ node = %(nodes)s
#@ tasks_per_node = %(ppn)s
#@ wall_clock_limit = %(walltime)s
#@ resources = ConsumableCpus(1) ConsumableMemory(%(ramproc)smb)
#@ notification = always
#@ notify_user = %(email)s
#@ job_type = parallel
#@ class = normal32
#@ node_usage = shared
#@ network.MPI = sn_all, shared, US
#@ output = stdout
#@ error = stderr
#@ queue

export MEMORY_AFFINITY=MCM
export MP_TASK_AFFINITY=MCM

cd %(rundir)r

echo "$( date ): %(code)s started" >> log
%(pre)s
poe hpmcount -nao prof/hpm %(bin)s
%(post)s
echo "$( date ): %(code)s finished" >> log

