#!/bin/bash
#PBS -q dque
#PBS -N cvm
#PBS -l nodes=252:ppn=2
#PBS -l walltime=00:10:00
#PBS -o out.log
#PBS -e err.log
#PBS -V
cd $HOME/sord/tmp
date > stamp0
mpirun -machinefile $PBS_NODEFILE -np 504 ./scecvm4-p
date > stamp1
