#!/bin/bash
#PBS -q workq
#PBS -N cvm
#PBS -l nodes=8:ppn=2
#PBS -l walltime=1:00:00
#PBS -o out.log
#PBS -e err.log
#PBS -V
sleep 2
cd /usr/localb/home/gely/sord/tmp
date > stamp0
time mpiexec -n 16 ./scecvm4-mpi
date > stamp1
