#!/bin/bash -e

cd "$( dirname $0 )"
srcdir=$( /bin/pwd )
cd ..
. sh/config
mkdir -p tmp
cd tmp

flags=$oflags

makes="\
  $sfc $flags $getarg asc2flt.f90 -o asc2flt
  $sfc $flags $getarg flt2asc.f90 -o flt2asc
  $sfc $flags $getarg swab.f90 -o swab
  $sfc $flags $getarg stats.f90 -o stats
  $sfc $flags drape.f90 -o drape
  $sfc $flags $getarg utm.f90 ll2utm.f90 -o ll2utm
  $sfc $flags utm.f90 tscoords.f90 tsgrid.f90 -o tsgrid
  $sfc $flags utm.f90 tscoords.f90 ts2ll.f90 -o ts2ll
  $sfc $flags utm.f90 tscoords.f90 ll2ts.f90 -o ll2ts
  $sfc $flags utm.f90 pscoords.f90 ps2ll.f90 -o ps2ll
  $sfc $flags utm.f90 pscoords.f90 ll2ps.f90 -o ll2ps
  $sfc $flags $getarg utm.f90 gearthdrape.f90 -o gearthdrape"

IFS_save=$IFS
IFS=${IFS// /}
makes=( $makes )
IFS=$IFS_save

for make in "${makes[@]}"; do
  set $make
  echo $make > state
  obj=${!#}
  files=""
  for arg in $*; do
  if [ "${arg#*.}" = f90 ]; then
    ln -s "$srcdir/$arg" &> /dev/null || :
    files="$files $arg"
    cat "$arg" >> state
  fi
  done
  compile=yes
  if [ -f $obj.state ]; then
    compile=$( cmp state $obj.state || : )
  fi
  if [ "$compile" ]; then
    echo $make
    $make
    mv state $obj.state
  fi
  rm -f $files *.o *.mod *.ipo *.il *.stb
done

