#!/bin/bash -e

IFS=":$IFS"
for dir in $PATH; do
for file in xlf95_r ifort pgf90 gfortran f95; do
  if [ -x $dir/$file ]; then
    sfc=$file
    break 2
  fi
done
done

pfc='mpif90'
case $sfc in
xlf95_r)
  sfc='xlf95_r -qsuffix=f=f90 -q64 -qsuppress=cmpmsg'
  pfc='mpxlf95_r -qsuffix=f=f90 -q64 -qsuppress=cmpmsg'
  gflags='-p -g -C -qflttrap -qsigtrap -qlanglvl=95pure'
  oflags='-O5'
  ;;
ifort)
  gflags='-O0 -p -g -CB -warn -traceback -u'
  oflags='-O3'
  ;;
pgf90)
  gflags='getarg-pgf.f90 -O0 -g -Ktrap=fp -Mbounds -Mdclchk -Mprof=lines'
  oflags='getarg-pgf.f90 -fast'
  ;;
gfortran)
  gflags='-O0 -p -g -W -pedantic -std=legacy -fbounds-check'
  gflags='-O0 -g -fbounds-check -ffpe-trap=invalid,zero,overflow,underflow'
  oflags='-O3'
  ;;
f95)  gflags='-g'
  oflags='-O'
  if [ $( uname ) = SunOS ]; then
    gflags='-g -w4 -u -C'
    oflags='-fast'
  fi
  ;;
*)
  echo "Error: no Fortran 95 compiler found"
  exit
esac

mkdir -p ../tmp/
cd ../tmp/
for file in ../util/*; do
  [ -e $( basename "$file" ) ] || ln -s "$file"
done
for file in ../data/*; do
  [ -e $( basename "$file" ) ] || ln -s "$file"
done

flags=$oflags

$sfc $flags swab.f90 -o swab
$sfc $flags drape.f90 -o drape
$sfc $flags stats.f90 -o stats
$sfc $flags bin2asc.f90 -o bin2asc
$sfc $flags utm.f90 tscoords.f90 ts2ll.f90 -o ts2ll
$sfc $flags utm.f90 tscoords.f90 ll2ts.f90 -o ll2ts
$sfc $flags utm.f90 tscoords.f90 tsg.f90 -o tsg
$sfc $flags utm.f90 tscoords.f90 tsr.f90 -o tsr

tar zxf scecvm4.tgz

$sfc -O3 iobin.f scecvm4.f -o scecvm
#$pfc iompi.f scecvm4.f -o scecvm

rm -f *.mod

