!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2_4954)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitm_cmucoords(f2pysetupfunc)
      use m_cmucoords, only : cmu2ll
      external f2pysetupfunc
      call f2pysetupfunc(cmu2ll)
      end subroutine f2pyinitm_cmucoords


