/* File: addmodule.c
 * This file is auto-generated with f2py (version:2_4954).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Fri Apr 18 23:42:30 2008
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include "fortranobject.h"
#include <string.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *add_error;
static PyObject *add_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#define STRINGMALLOC(str,len)\
  if ((str = (string)malloc(sizeof(char)*(len+1))) == NULL) {\
    PyErr_SetString(PyExc_MemoryError, "out of memory");\
    goto capi_fail;\
  } else {\
    (str)[len] = '\0';\
  }

#define PRINTPYOBJERR(obj)\
  fprintf(stderr,"add.error is related to ");\
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");

\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (((PyArrayObject *)(capi_ ## var ## _tmp))->nd)
#define old_shape(var,dim) (((PyArrayObject *)(capi_ ## var ## _tmp))->dimensions[dim])
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define STRINGCOPYN(to,from,buf_size)                           \
    do {                                                        \
        int _m = (buf_size);                                    \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, sizeof(char)*_m);             \
        _to[_m-1] = '\0';                                      \
        /* Padding with spaces instead of nulls */              \
        for (_m -= 2; _m >= 0 && _to[_m] == '\0'; _m--) {      \
            _to[_m] = ' ';                                      \
        }                                                       \
    } while (0)


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = add_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = add_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int float_from_pyobj(float* v,PyObject *obj,const char *errmess) {
  double d=0.0;
  if (double_from_pyobj(&d,obj,errmess)) {
    *v = (float)d;
    return 1;
  }
  return 0;
}

static int try_pyarr_from_string(PyObject *obj,const string str) {
  PyArrayObject *arr = NULL;
  if (PyArray_Check(obj) && (!((arr = (PyArrayObject *)obj) == NULL)))
    { STRINGCOPYN(arr->data,str,PyArray_NBYTES(arr)); }
  return 1;
capi_fail:
  PRINTPYOBJERR(obj);
  PyErr_SetString(add_error,"try_pyarr_from_string failed");
  return 0;
}

static int string_from_pyobj(string *str,int *len,const string inistr,PyObject *obj,const char *errmess) {
  PyArrayObject *arr = NULL;
  PyObject *tmp = NULL;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",(char*)str,*len,(char *)inistr,obj);
#endif
  if (obj == Py_None) {
    if (*len == -1)
      *len = strlen(inistr); /* Will this cause problems? */
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,inistr,*len+1);
    return 1;
  }
  if (PyArray_Check(obj)) {
    if ((arr = (PyArrayObject *)obj) == NULL)
      goto capi_fail;
    if (!ISCONTIGUOUS(arr)) {
      PyErr_SetString(PyExc_ValueError,"array object is non-contiguous.");
      goto capi_fail;
    }
    if (*len == -1)
      *len = (arr->descr->elsize)*PyArray_SIZE(arr);
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,arr->data,*len+1);
    return 1;
  }
  if (PyString_Check(obj)) {
    tmp = obj;
    Py_INCREF(tmp);
  }
  else
    tmp = PyObject_Str(obj);
  if (tmp == NULL) goto capi_fail;
  if (*len == -1)
    *len = PyString_GET_SIZE(tmp);
  STRINGMALLOC(*str,*len);
  STRINGCOPYN(*str,PyString_AS_STRING(tmp),*len+1);
  Py_DECREF(tmp);
  return 1;
capi_fail:
  Py_XDECREF(tmp);
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = add_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/************************************ zone ************************************/
static char doc_f2py_rout_add_m_util_zone[] = "\
Function signature:\n\
  zone(i1,i2,nn,nnoff,ihypo,faultnormal)\n\
Required arguments:\n"
"  i1 : in/output rank-1 array('i') with bounds (3)\n"
"  i2 : in/output rank-1 array('i') with bounds (3)\n"
"  nn : input rank-1 array('i') with bounds (3)\n"
"  nnoff : input rank-1 array('i') with bounds (3)\n"
"  ihypo : input rank-1 array('i') with bounds (3)\n"
"  faultnormal : input int";
/*  */
static PyObject *f2py_rout_add_m_util_zone(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int *i1 = NULL;
  npy_intp i1_Dims[1] = {-1};
  const int i1_Rank = 1;
  PyArrayObject *capi_i1_tmp = NULL;
  int capi_i1_intent = 0;
  PyObject *i1_capi = Py_None;
  int *i2 = NULL;
  npy_intp i2_Dims[1] = {-1};
  const int i2_Rank = 1;
  PyArrayObject *capi_i2_tmp = NULL;
  int capi_i2_intent = 0;
  PyObject *i2_capi = Py_None;
  int *nn = NULL;
  npy_intp nn_Dims[1] = {-1};
  const int nn_Rank = 1;
  PyArrayObject *capi_nn_tmp = NULL;
  int capi_nn_intent = 0;
  PyObject *nn_capi = Py_None;
  int *nnoff = NULL;
  npy_intp nnoff_Dims[1] = {-1};
  const int nnoff_Rank = 1;
  PyArrayObject *capi_nnoff_tmp = NULL;
  int capi_nnoff_intent = 0;
  PyObject *nnoff_capi = Py_None;
  int *ihypo = NULL;
  npy_intp ihypo_Dims[1] = {-1};
  const int ihypo_Rank = 1;
  PyArrayObject *capi_ihypo_tmp = NULL;
  int capi_ihypo_intent = 0;
  PyObject *ihypo_capi = Py_None;
  int faultnormal = 0;
  PyObject *faultnormal_capi = Py_None;
  static char *capi_kwlist[] = {"i1","i2","nn","nnoff","ihypo","faultnormal",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO|:add.m_util.zone",\
    capi_kwlist,&i1_capi,&i2_capi,&nn_capi,&nnoff_capi,&ihypo_capi,&faultnormal_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable faultnormal */
    f2py_success = int_from_pyobj(&faultnormal,faultnormal_capi,"add.m_util.zone() 6th argument (faultnormal) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nn */
  nn_Dims[0]=3;
  capi_nn_intent |= F2PY_INTENT_IN;
  capi_nn_tmp = array_from_pyobj(PyArray_INT,nn_Dims,nn_Rank,capi_nn_intent,nn_capi);
  if (capi_nn_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 3rd argument `nn' of add.m_util.zone to C/Fortran array" );
  } else {
    nn = (int *)(capi_nn_tmp->data);

  /* Processing variable i1 */
  i1_Dims[0]=3;
  capi_i1_intent |= F2PY_INTENT_INOUT;
  capi_i1_tmp = array_from_pyobj(PyArray_INT,i1_Dims,i1_Rank,capi_i1_intent,i1_capi);
  if (capi_i1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 1st argument `i1' of add.m_util.zone to C/Fortran array" );
  } else {
    i1 = (int *)(capi_i1_tmp->data);

  /* Processing variable i2 */
  i2_Dims[0]=3;
  capi_i2_intent |= F2PY_INTENT_INOUT;
  capi_i2_tmp = array_from_pyobj(PyArray_INT,i2_Dims,i2_Rank,capi_i2_intent,i2_capi);
  if (capi_i2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 2nd argument `i2' of add.m_util.zone to C/Fortran array" );
  } else {
    i2 = (int *)(capi_i2_tmp->data);

  /* Processing variable nnoff */
  nnoff_Dims[0]=3;
  capi_nnoff_intent |= F2PY_INTENT_IN;
  capi_nnoff_tmp = array_from_pyobj(PyArray_INT,nnoff_Dims,nnoff_Rank,capi_nnoff_intent,nnoff_capi);
  if (capi_nnoff_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 4th argument `nnoff' of add.m_util.zone to C/Fortran array" );
  } else {
    nnoff = (int *)(capi_nnoff_tmp->data);

  /* Processing variable ihypo */
  ihypo_Dims[0]=3;
  capi_ihypo_intent |= F2PY_INTENT_IN;
  capi_ihypo_tmp = array_from_pyobj(PyArray_INT,ihypo_Dims,ihypo_Rank,capi_ihypo_intent,ihypo_capi);
  if (capi_ihypo_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 5th argument `ihypo' of add.m_util.zone to C/Fortran array" );
  } else {
    ihypo = (int *)(capi_ihypo_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(i1,i2,nn,nnoff,ihypo,&faultnormal);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_ihypo_tmp!=ihypo_capi) {
    Py_XDECREF(capi_ihypo_tmp); }
  }  /*if (capi_ihypo_tmp == NULL) ... else of ihypo*/
  /* End of cleaning variable ihypo */
  if((PyObject *)capi_nnoff_tmp!=nnoff_capi) {
    Py_XDECREF(capi_nnoff_tmp); }
  }  /*if (capi_nnoff_tmp == NULL) ... else of nnoff*/
  /* End of cleaning variable nnoff */
  if((PyObject *)capi_i2_tmp!=i2_capi) {
    Py_XDECREF(capi_i2_tmp); }
  }  /*if (capi_i2_tmp == NULL) ... else of i2*/
  /* End of cleaning variable i2 */
  if((PyObject *)capi_i1_tmp!=i1_capi) {
    Py_XDECREF(capi_i1_tmp); }
  }  /*if (capi_i1_tmp == NULL) ... else of i1*/
  /* End of cleaning variable i1 */
  if((PyObject *)capi_nn_tmp!=nn_capi) {
    Py_XDECREF(capi_nn_tmp); }
  }  /*if (capi_nn_tmp == NULL) ... else of nn*/
  /* End of cleaning variable nn */
  } /*if (f2py_success) of faultnormal*/
  /* End of cleaning variable faultnormal */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of zone ********************************/

/************************************ cube ************************************/
static char doc_f2py_rout_add_m_util_cube[] = "\
Function signature:\n\
  cube(f,x,i1,i2,x1,x2,r)\n\
Required arguments:\n"
"  f : in/output rank-3 array('f') with bounds (:,:,:)\n"
"  x : input rank-4 array('f') with bounds (:,:,:,:)\n"
"  i1 : input rank-1 array('i') with bounds (3)\n"
"  i2 : input rank-1 array('i') with bounds (3)\n"
"  x1 : input rank-1 array('f') with bounds (3)\n"
"  x2 : input rank-1 array('f') with bounds (3)\n"
"  r : input float";
/*  */
static PyObject *f2py_rout_add_m_util_cube(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,int*,int*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float *f = NULL;
  npy_intp f_Dims[3] = {-1, -1, -1};
  const int f_Rank = 3;
  PyArrayObject *capi_f_tmp = NULL;
  int capi_f_intent = 0;
  PyObject *f_capi = Py_None;
  float *x = NULL;
  npy_intp x_Dims[4] = {-1, -1, -1, -1};
  const int x_Rank = 4;
  PyArrayObject *capi_x_tmp = NULL;
  int capi_x_intent = 0;
  PyObject *x_capi = Py_None;
  int *i1 = NULL;
  npy_intp i1_Dims[1] = {-1};
  const int i1_Rank = 1;
  PyArrayObject *capi_i1_tmp = NULL;
  int capi_i1_intent = 0;
  PyObject *i1_capi = Py_None;
  int *i2 = NULL;
  npy_intp i2_Dims[1] = {-1};
  const int i2_Rank = 1;
  PyArrayObject *capi_i2_tmp = NULL;
  int capi_i2_intent = 0;
  PyObject *i2_capi = Py_None;
  float *x1 = NULL;
  npy_intp x1_Dims[1] = {-1};
  const int x1_Rank = 1;
  PyArrayObject *capi_x1_tmp = NULL;
  int capi_x1_intent = 0;
  PyObject *x1_capi = Py_None;
  float *x2 = NULL;
  npy_intp x2_Dims[1] = {-1};
  const int x2_Rank = 1;
  PyArrayObject *capi_x2_tmp = NULL;
  int capi_x2_intent = 0;
  PyObject *x2_capi = Py_None;
  float r = 0;
  PyObject *r_capi = Py_None;
  static char *capi_kwlist[] = {"f","x","i1","i2","x1","x2","r",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOO|:add.m_util.cube",\
    capi_kwlist,&f_capi,&x_capi,&i1_capi,&i2_capi,&x1_capi,&x2_capi,&r_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable i2 */
  i2_Dims[0]=3;
  capi_i2_intent |= F2PY_INTENT_IN;
  capi_i2_tmp = array_from_pyobj(PyArray_INT,i2_Dims,i2_Rank,capi_i2_intent,i2_capi);
  if (capi_i2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 4th argument `i2' of add.m_util.cube to C/Fortran array" );
  } else {
    i2 = (int *)(capi_i2_tmp->data);

  /* Processing variable f */
  ;
  capi_f_intent |= F2PY_INTENT_INOUT;
  capi_f_tmp = array_from_pyobj(PyArray_FLOAT,f_Dims,f_Rank,capi_f_intent,f_capi);
  if (capi_f_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 1st argument `f' of add.m_util.cube to C/Fortran array" );
  } else {
    f = (float *)(capi_f_tmp->data);

  /* Processing variable i1 */
  i1_Dims[0]=3;
  capi_i1_intent |= F2PY_INTENT_IN;
  capi_i1_tmp = array_from_pyobj(PyArray_INT,i1_Dims,i1_Rank,capi_i1_intent,i1_capi);
  if (capi_i1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 3rd argument `i1' of add.m_util.cube to C/Fortran array" );
  } else {
    i1 = (int *)(capi_i1_tmp->data);

  /* Processing variable r */
    f2py_success = float_from_pyobj(&r,r_capi,"add.m_util.cube() 7th argument (r) can't be converted to float");
  if (f2py_success) {
  /* Processing variable x2 */
  x2_Dims[0]=3;
  capi_x2_intent |= F2PY_INTENT_IN;
  capi_x2_tmp = array_from_pyobj(PyArray_FLOAT,x2_Dims,x2_Rank,capi_x2_intent,x2_capi);
  if (capi_x2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 6th argument `x2' of add.m_util.cube to C/Fortran array" );
  } else {
    x2 = (float *)(capi_x2_tmp->data);

  /* Processing variable x */
  ;
  capi_x_intent |= F2PY_INTENT_IN;
  capi_x_tmp = array_from_pyobj(PyArray_FLOAT,x_Dims,x_Rank,capi_x_intent,x_capi);
  if (capi_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 2nd argument `x' of add.m_util.cube to C/Fortran array" );
  } else {
    x = (float *)(capi_x_tmp->data);

  /* Processing variable x1 */
  x1_Dims[0]=3;
  capi_x1_intent |= F2PY_INTENT_IN;
  capi_x1_tmp = array_from_pyobj(PyArray_FLOAT,x1_Dims,x1_Rank,capi_x1_intent,x1_capi);
  if (capi_x1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 5th argument `x1' of add.m_util.cube to C/Fortran array" );
  } else {
    x1 = (float *)(capi_x1_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(f,x,i1,i2,x1,x2,&r);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_x1_tmp!=x1_capi) {
    Py_XDECREF(capi_x1_tmp); }
  }  /*if (capi_x1_tmp == NULL) ... else of x1*/
  /* End of cleaning variable x1 */
  if((PyObject *)capi_x_tmp!=x_capi) {
    Py_XDECREF(capi_x_tmp); }
  }  /*if (capi_x_tmp == NULL) ... else of x*/
  /* End of cleaning variable x */
  if((PyObject *)capi_x2_tmp!=x2_capi) {
    Py_XDECREF(capi_x2_tmp); }
  }  /*if (capi_x2_tmp == NULL) ... else of x2*/
  /* End of cleaning variable x2 */
  } /*if (f2py_success) of r*/
  /* End of cleaning variable r */
  if((PyObject *)capi_i1_tmp!=i1_capi) {
    Py_XDECREF(capi_i1_tmp); }
  }  /*if (capi_i1_tmp == NULL) ... else of i1*/
  /* End of cleaning variable i1 */
  if((PyObject *)capi_f_tmp!=f_capi) {
    Py_XDECREF(capi_f_tmp); }
  }  /*if (capi_f_tmp == NULL) ... else of f*/
  /* End of cleaning variable f */
  if((PyObject *)capi_i2_tmp!=i2_capi) {
    Py_XDECREF(capi_i2_tmp); }
  }  /*if (capi_i2_tmp == NULL) ... else of i2*/
  /* End of cleaning variable i2 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of cube ********************************/

/*********************************** invert ***********************************/
static char doc_f2py_rout_add_m_util_invert[] = "\
Function signature:\n\
  invert(f)\n\
Required arguments:\n"
"  f : in/output rank-3 array('f') with bounds (:,:,:)";
/*  */
static PyObject *f2py_rout_add_m_util_invert(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float *f = NULL;
  npy_intp f_Dims[3] = {-1, -1, -1};
  const int f_Rank = 3;
  PyArrayObject *capi_f_tmp = NULL;
  int capi_f_intent = 0;
  PyObject *f_capi = Py_None;
  static char *capi_kwlist[] = {"f",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O|:add.m_util.invert",\
    capi_kwlist,&f_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable f */
  ;
  capi_f_intent |= F2PY_INTENT_INOUT;
  capi_f_tmp = array_from_pyobj(PyArray_FLOAT,f_Dims,f_Rank,capi_f_intent,f_capi);
  if (capi_f_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 1st argument `f' of add.m_util.invert to C/Fortran array" );
  } else {
    f = (float *)(capi_f_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(f);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_f_tmp!=f_capi) {
    Py_XDECREF(capi_f_tmp); }
  }  /*if (capi_f_tmp == NULL) ... else of f*/
  /* End of cleaning variable f */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of invert *******************************/

/******************************* scalaraverage *******************************/
static char doc_f2py_rout_add_m_util_scalaraverage[] = "\
Function signature:\n\
  f2 = scalaraverage(f1,i1,i2,d)\n\
Required arguments:\n"
"  f1 : input rank-3 array('f') with bounds (:,:,:)\n"
"  i1 : input rank-1 array('i') with bounds (3)\n"
"  i2 : input rank-1 array('i') with bounds (3)\n"
"  d : input int\n"
"Return objects:\n"
"  f2 : rank-3 array('f') with bounds (:,:,:)";
/*  */
static PyObject *f2py_rout_add_m_util_scalaraverage(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float *f2 = NULL;
  npy_intp f2_Dims[3] = {-1, -1, -1};
  const int f2_Rank = 3;
  PyArrayObject *capi_f2_tmp = NULL;
  int capi_f2_intent = 0;
  float *f1 = NULL;
  npy_intp f1_Dims[3] = {-1, -1, -1};
  const int f1_Rank = 3;
  PyArrayObject *capi_f1_tmp = NULL;
  int capi_f1_intent = 0;
  PyObject *f1_capi = Py_None;
  int *i1 = NULL;
  npy_intp i1_Dims[1] = {-1};
  const int i1_Rank = 1;
  PyArrayObject *capi_i1_tmp = NULL;
  int capi_i1_intent = 0;
  PyObject *i1_capi = Py_None;
  int *i2 = NULL;
  npy_intp i2_Dims[1] = {-1};
  const int i2_Rank = 1;
  PyArrayObject *capi_i2_tmp = NULL;
  int capi_i2_intent = 0;
  PyObject *i2_capi = Py_None;
  int d = 0;
  PyObject *d_capi = Py_None;
  static char *capi_kwlist[] = {"f1","i1","i2","d",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO|:add.m_util.scalaraverage",\
    capi_kwlist,&f1_capi,&i1_capi,&i2_capi,&d_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable f1 */
  ;
  capi_f1_intent |= F2PY_INTENT_IN;
  capi_f1_tmp = array_from_pyobj(PyArray_FLOAT,f1_Dims,f1_Rank,capi_f1_intent,f1_capi);
  if (capi_f1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 1st argument `f1' of add.m_util.scalaraverage to C/Fortran array" );
  } else {
    f1 = (float *)(capi_f1_tmp->data);

  /* Processing variable f2 */
  ;
  capi_f2_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_f2_tmp = array_from_pyobj(PyArray_FLOAT,f2_Dims,f2_Rank,capi_f2_intent,Py_None);
  if (capi_f2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting hidden `f2' of add.m_util.scalaraverage to C/Fortran array" );
  } else {
    f2 = (float *)(capi_f2_tmp->data);

  /* Processing variable i2 */
  i2_Dims[0]=3;
  capi_i2_intent |= F2PY_INTENT_IN;
  capi_i2_tmp = array_from_pyobj(PyArray_INT,i2_Dims,i2_Rank,capi_i2_intent,i2_capi);
  if (capi_i2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 3rd argument `i2' of add.m_util.scalaraverage to C/Fortran array" );
  } else {
    i2 = (int *)(capi_i2_tmp->data);

  /* Processing variable d */
    f2py_success = int_from_pyobj(&d,d_capi,"add.m_util.scalaraverage() 4th argument (d) can't be converted to int");
  if (f2py_success) {
  /* Processing variable i1 */
  i1_Dims[0]=3;
  capi_i1_intent |= F2PY_INTENT_IN;
  capi_i1_tmp = array_from_pyobj(PyArray_INT,i1_Dims,i1_Rank,capi_i1_intent,i1_capi);
  if (capi_i1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 2nd argument `i1' of add.m_util.scalaraverage to C/Fortran array" );
  } else {
    i1 = (int *)(capi_i1_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(f2,f1,i1,i2,&d);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_f2_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_i1_tmp!=i1_capi) {
    Py_XDECREF(capi_i1_tmp); }
  }  /*if (capi_i1_tmp == NULL) ... else of i1*/
  /* End of cleaning variable i1 */
  } /*if (f2py_success) of d*/
  /* End of cleaning variable d */
  if((PyObject *)capi_i2_tmp!=i2_capi) {
    Py_XDECREF(capi_i2_tmp); }
  }  /*if (capi_i2_tmp == NULL) ... else of i2*/
  /* End of cleaning variable i2 */
  }  /*if (capi_f2_tmp == NULL) ... else of f2*/
  /* End of cleaning variable f2 */
  if((PyObject *)capi_f1_tmp!=f1_capi) {
    Py_XDECREF(capi_f1_tmp); }
  }  /*if (capi_f1_tmp == NULL) ... else of f1*/
  /* End of cleaning variable f1 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of scalaraverage ****************************/

/******************************* vectoraverage *******************************/
static char doc_f2py_rout_add_m_util_vectoraverage[] = "\
Function signature:\n\
  f2 = vectoraverage(f1,i1,i2,d)\n\
Required arguments:\n"
"  f1 : input rank-4 array('f') with bounds (:,:,:,:)\n"
"  i1 : input rank-1 array('i') with bounds (3)\n"
"  i2 : input rank-1 array('i') with bounds (3)\n"
"  d : input int\n"
"Return objects:\n"
"  f2 : rank-4 array('f') with bounds (:,:,:,:)";
/*  */
static PyObject *f2py_rout_add_m_util_vectoraverage(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float *f2 = NULL;
  npy_intp f2_Dims[4] = {-1, -1, -1, -1};
  const int f2_Rank = 4;
  PyArrayObject *capi_f2_tmp = NULL;
  int capi_f2_intent = 0;
  float *f1 = NULL;
  npy_intp f1_Dims[4] = {-1, -1, -1, -1};
  const int f1_Rank = 4;
  PyArrayObject *capi_f1_tmp = NULL;
  int capi_f1_intent = 0;
  PyObject *f1_capi = Py_None;
  int *i1 = NULL;
  npy_intp i1_Dims[1] = {-1};
  const int i1_Rank = 1;
  PyArrayObject *capi_i1_tmp = NULL;
  int capi_i1_intent = 0;
  PyObject *i1_capi = Py_None;
  int *i2 = NULL;
  npy_intp i2_Dims[1] = {-1};
  const int i2_Rank = 1;
  PyArrayObject *capi_i2_tmp = NULL;
  int capi_i2_intent = 0;
  PyObject *i2_capi = Py_None;
  int d = 0;
  PyObject *d_capi = Py_None;
  static char *capi_kwlist[] = {"f1","i1","i2","d",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO|:add.m_util.vectoraverage",\
    capi_kwlist,&f1_capi,&i1_capi,&i2_capi,&d_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable f1 */
  ;
  capi_f1_intent |= F2PY_INTENT_IN;
  capi_f1_tmp = array_from_pyobj(PyArray_FLOAT,f1_Dims,f1_Rank,capi_f1_intent,f1_capi);
  if (capi_f1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 1st argument `f1' of add.m_util.vectoraverage to C/Fortran array" );
  } else {
    f1 = (float *)(capi_f1_tmp->data);

  /* Processing variable f2 */
  ;
  capi_f2_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_f2_tmp = array_from_pyobj(PyArray_FLOAT,f2_Dims,f2_Rank,capi_f2_intent,Py_None);
  if (capi_f2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting hidden `f2' of add.m_util.vectoraverage to C/Fortran array" );
  } else {
    f2 = (float *)(capi_f2_tmp->data);

  /* Processing variable i2 */
  i2_Dims[0]=3;
  capi_i2_intent |= F2PY_INTENT_IN;
  capi_i2_tmp = array_from_pyobj(PyArray_INT,i2_Dims,i2_Rank,capi_i2_intent,i2_capi);
  if (capi_i2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 3rd argument `i2' of add.m_util.vectoraverage to C/Fortran array" );
  } else {
    i2 = (int *)(capi_i2_tmp->data);

  /* Processing variable d */
    f2py_success = int_from_pyobj(&d,d_capi,"add.m_util.vectoraverage() 4th argument (d) can't be converted to int");
  if (f2py_success) {
  /* Processing variable i1 */
  i1_Dims[0]=3;
  capi_i1_intent |= F2PY_INTENT_IN;
  capi_i1_tmp = array_from_pyobj(PyArray_INT,i1_Dims,i1_Rank,capi_i1_intent,i1_capi);
  if (capi_i1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 2nd argument `i1' of add.m_util.vectoraverage to C/Fortran array" );
  } else {
    i1 = (int *)(capi_i1_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(f2,f1,i1,i2,&d);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_f2_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_i1_tmp!=i1_capi) {
    Py_XDECREF(capi_i1_tmp); }
  }  /*if (capi_i1_tmp == NULL) ... else of i1*/
  /* End of cleaning variable i1 */
  } /*if (f2py_success) of d*/
  /* End of cleaning variable d */
  if((PyObject *)capi_i2_tmp!=i2_capi) {
    Py_XDECREF(capi_i2_tmp); }
  }  /*if (capi_i2_tmp == NULL) ... else of i2*/
  /* End of cleaning variable i2 */
  }  /*if (capi_f2_tmp == NULL) ... else of f2*/
  /* End of cleaning variable f2 */
  if((PyObject *)capi_f1_tmp!=f1_capi) {
    Py_XDECREF(capi_f1_tmp); }
  }  /*if (capi_f1_tmp == NULL) ... else of f1*/
  /* End of cleaning variable f1 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of vectoraverage ****************************/

/*********************************** radius ***********************************/
static char doc_f2py_rout_add_m_util_radius[] = "\
Function signature:\n\
  r = radius(x,x0,i1,i2)\n\
Required arguments:\n"
"  x : input rank-4 array('f') with bounds (:,:,:,:)\n"
"  x0 : input rank-1 array('f') with bounds (3)\n"
"  i1 : input rank-1 array('i') with bounds (3)\n"
"  i2 : input rank-1 array('i') with bounds (3)\n"
"Return objects:\n"
"  r : rank-3 array('f') with bounds (:,:,:)";
/*  */
static PyObject *f2py_rout_add_m_util_radius(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,float*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float *r = NULL;
  npy_intp r_Dims[3] = {-1, -1, -1};
  const int r_Rank = 3;
  PyArrayObject *capi_r_tmp = NULL;
  int capi_r_intent = 0;
  float *x = NULL;
  npy_intp x_Dims[4] = {-1, -1, -1, -1};
  const int x_Rank = 4;
  PyArrayObject *capi_x_tmp = NULL;
  int capi_x_intent = 0;
  PyObject *x_capi = Py_None;
  float *x0 = NULL;
  npy_intp x0_Dims[1] = {-1};
  const int x0_Rank = 1;
  PyArrayObject *capi_x0_tmp = NULL;
  int capi_x0_intent = 0;
  PyObject *x0_capi = Py_None;
  int *i1 = NULL;
  npy_intp i1_Dims[1] = {-1};
  const int i1_Rank = 1;
  PyArrayObject *capi_i1_tmp = NULL;
  int capi_i1_intent = 0;
  PyObject *i1_capi = Py_None;
  int *i2 = NULL;
  npy_intp i2_Dims[1] = {-1};
  const int i2_Rank = 1;
  PyArrayObject *capi_i2_tmp = NULL;
  int capi_i2_intent = 0;
  PyObject *i2_capi = Py_None;
  static char *capi_kwlist[] = {"x","x0","i1","i2",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO|:add.m_util.radius",\
    capi_kwlist,&x_capi,&x0_capi,&i1_capi,&i2_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable i2 */
  i2_Dims[0]=3;
  capi_i2_intent |= F2PY_INTENT_IN;
  capi_i2_tmp = array_from_pyobj(PyArray_INT,i2_Dims,i2_Rank,capi_i2_intent,i2_capi);
  if (capi_i2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 4th argument `i2' of add.m_util.radius to C/Fortran array" );
  } else {
    i2 = (int *)(capi_i2_tmp->data);

  /* Processing variable i1 */
  i1_Dims[0]=3;
  capi_i1_intent |= F2PY_INTENT_IN;
  capi_i1_tmp = array_from_pyobj(PyArray_INT,i1_Dims,i1_Rank,capi_i1_intent,i1_capi);
  if (capi_i1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 3rd argument `i1' of add.m_util.radius to C/Fortran array" );
  } else {
    i1 = (int *)(capi_i1_tmp->data);

  /* Processing variable r */
  ;
  capi_r_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_r_tmp = array_from_pyobj(PyArray_FLOAT,r_Dims,r_Rank,capi_r_intent,Py_None);
  if (capi_r_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting hidden `r' of add.m_util.radius to C/Fortran array" );
  } else {
    r = (float *)(capi_r_tmp->data);

  /* Processing variable x */
  ;
  capi_x_intent |= F2PY_INTENT_IN;
  capi_x_tmp = array_from_pyobj(PyArray_FLOAT,x_Dims,x_Rank,capi_x_intent,x_capi);
  if (capi_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 1st argument `x' of add.m_util.radius to C/Fortran array" );
  } else {
    x = (float *)(capi_x_tmp->data);

  /* Processing variable x0 */
  x0_Dims[0]=3;
  capi_x0_intent |= F2PY_INTENT_IN;
  capi_x0_tmp = array_from_pyobj(PyArray_FLOAT,x0_Dims,x0_Rank,capi_x0_intent,x0_capi);
  if (capi_x0_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 2nd argument `x0' of add.m_util.radius to C/Fortran array" );
  } else {
    x0 = (float *)(capi_x0_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(r,x,x0,i1,i2);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_r_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_x0_tmp!=x0_capi) {
    Py_XDECREF(capi_x0_tmp); }
  }  /*if (capi_x0_tmp == NULL) ... else of x0*/
  /* End of cleaning variable x0 */
  if((PyObject *)capi_x_tmp!=x_capi) {
    Py_XDECREF(capi_x_tmp); }
  }  /*if (capi_x_tmp == NULL) ... else of x*/
  /* End of cleaning variable x */
  }  /*if (capi_r_tmp == NULL) ... else of r*/
  /* End of cleaning variable r */
  if((PyObject *)capi_i1_tmp!=i1_capi) {
    Py_XDECREF(capi_i1_tmp); }
  }  /*if (capi_i1_tmp == NULL) ... else of i1*/
  /* End of cleaning variable i1 */
  if((PyObject *)capi_i2_tmp!=i2_capi) {
    Py_XDECREF(capi_i2_tmp); }
  }  /*if (capi_i2_tmp == NULL) ... else of i2*/
  /* End of cleaning variable i2 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of radius *******************************/

/********************************* vectornorm *********************************/
static char doc_f2py_rout_add_m_util_vectornorm[] = "\
Function signature:\n\
  s = vectornorm(f,i1,i2)\n\
Required arguments:\n"
"  f : input rank-4 array('f') with bounds (:,:,:,:)\n"
"  i1 : input rank-1 array('i') with bounds (3)\n"
"  i2 : input rank-1 array('i') with bounds (3)\n"
"Return objects:\n"
"  s : rank-3 array('f') with bounds (:,:,:)";
/*  */
static PyObject *f2py_rout_add_m_util_vectornorm(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float *s = NULL;
  npy_intp s_Dims[3] = {-1, -1, -1};
  const int s_Rank = 3;
  PyArrayObject *capi_s_tmp = NULL;
  int capi_s_intent = 0;
  float *f = NULL;
  npy_intp f_Dims[4] = {-1, -1, -1, -1};
  const int f_Rank = 4;
  PyArrayObject *capi_f_tmp = NULL;
  int capi_f_intent = 0;
  PyObject *f_capi = Py_None;
  int *i1 = NULL;
  npy_intp i1_Dims[1] = {-1};
  const int i1_Rank = 1;
  PyArrayObject *capi_i1_tmp = NULL;
  int capi_i1_intent = 0;
  PyObject *i1_capi = Py_None;
  int *i2 = NULL;
  npy_intp i2_Dims[1] = {-1};
  const int i2_Rank = 1;
  PyArrayObject *capi_i2_tmp = NULL;
  int capi_i2_intent = 0;
  PyObject *i2_capi = Py_None;
  static char *capi_kwlist[] = {"f","i1","i2",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO|:add.m_util.vectornorm",\
    capi_kwlist,&f_capi,&i1_capi,&i2_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable i2 */
  i2_Dims[0]=3;
  capi_i2_intent |= F2PY_INTENT_IN;
  capi_i2_tmp = array_from_pyobj(PyArray_INT,i2_Dims,i2_Rank,capi_i2_intent,i2_capi);
  if (capi_i2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 3rd argument `i2' of add.m_util.vectornorm to C/Fortran array" );
  } else {
    i2 = (int *)(capi_i2_tmp->data);

  /* Processing variable f */
  ;
  capi_f_intent |= F2PY_INTENT_IN;
  capi_f_tmp = array_from_pyobj(PyArray_FLOAT,f_Dims,f_Rank,capi_f_intent,f_capi);
  if (capi_f_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 1st argument `f' of add.m_util.vectornorm to C/Fortran array" );
  } else {
    f = (float *)(capi_f_tmp->data);

  /* Processing variable i1 */
  i1_Dims[0]=3;
  capi_i1_intent |= F2PY_INTENT_IN;
  capi_i1_tmp = array_from_pyobj(PyArray_INT,i1_Dims,i1_Rank,capi_i1_intent,i1_capi);
  if (capi_i1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 2nd argument `i1' of add.m_util.vectornorm to C/Fortran array" );
  } else {
    i1 = (int *)(capi_i1_tmp->data);

  /* Processing variable s */
  ;
  capi_s_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_s_tmp = array_from_pyobj(PyArray_FLOAT,s_Dims,s_Rank,capi_s_intent,Py_None);
  if (capi_s_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting hidden `s' of add.m_util.vectornorm to C/Fortran array" );
  } else {
    s = (float *)(capi_s_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(s,f,i1,i2);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_s_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_s_tmp == NULL) ... else of s*/
  /* End of cleaning variable s */
  if((PyObject *)capi_i1_tmp!=i1_capi) {
    Py_XDECREF(capi_i1_tmp); }
  }  /*if (capi_i1_tmp == NULL) ... else of i1*/
  /* End of cleaning variable i1 */
  if((PyObject *)capi_f_tmp!=f_capi) {
    Py_XDECREF(capi_f_tmp); }
  }  /*if (capi_f_tmp == NULL) ... else of f*/
  /* End of cleaning variable f */
  if((PyObject *)capi_i2_tmp!=i2_capi) {
    Py_XDECREF(capi_i2_tmp); }
  }  /*if (capi_i2_tmp == NULL) ... else of i2*/
  /* End of cleaning variable i2 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of vectornorm *****************************/

/********************************* tensornorm *********************************/
static char doc_f2py_rout_add_m_util_tensornorm[] = "\
Function signature:\n\
  s = tensornorm(f1,f2,i1,i2)\n\
Required arguments:\n"
"  f1 : input rank-4 array('f') with bounds (:,:,:,:)\n"
"  f2 : input rank-4 array('f') with bounds (:,:,:,:)\n"
"  i1 : input rank-1 array('i') with bounds (3)\n"
"  i2 : input rank-1 array('i') with bounds (3)\n"
"Return objects:\n"
"  s : rank-3 array('f') with bounds (:,:,:)";
/*  */
static PyObject *f2py_rout_add_m_util_tensornorm(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,float*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float *s = NULL;
  npy_intp s_Dims[3] = {-1, -1, -1};
  const int s_Rank = 3;
  PyArrayObject *capi_s_tmp = NULL;
  int capi_s_intent = 0;
  float *f1 = NULL;
  npy_intp f1_Dims[4] = {-1, -1, -1, -1};
  const int f1_Rank = 4;
  PyArrayObject *capi_f1_tmp = NULL;
  int capi_f1_intent = 0;
  PyObject *f1_capi = Py_None;
  float *f2 = NULL;
  npy_intp f2_Dims[4] = {-1, -1, -1, -1};
  const int f2_Rank = 4;
  PyArrayObject *capi_f2_tmp = NULL;
  int capi_f2_intent = 0;
  PyObject *f2_capi = Py_None;
  int *i1 = NULL;
  npy_intp i1_Dims[1] = {-1};
  const int i1_Rank = 1;
  PyArrayObject *capi_i1_tmp = NULL;
  int capi_i1_intent = 0;
  PyObject *i1_capi = Py_None;
  int *i2 = NULL;
  npy_intp i2_Dims[1] = {-1};
  const int i2_Rank = 1;
  PyArrayObject *capi_i2_tmp = NULL;
  int capi_i2_intent = 0;
  PyObject *i2_capi = Py_None;
  static char *capi_kwlist[] = {"f1","f2","i1","i2",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO|:add.m_util.tensornorm",\
    capi_kwlist,&f1_capi,&f2_capi,&i1_capi,&i2_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable f1 */
  ;
  capi_f1_intent |= F2PY_INTENT_IN;
  capi_f1_tmp = array_from_pyobj(PyArray_FLOAT,f1_Dims,f1_Rank,capi_f1_intent,f1_capi);
  if (capi_f1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 1st argument `f1' of add.m_util.tensornorm to C/Fortran array" );
  } else {
    f1 = (float *)(capi_f1_tmp->data);

  /* Processing variable f2 */
  ;
  capi_f2_intent |= F2PY_INTENT_IN;
  capi_f2_tmp = array_from_pyobj(PyArray_FLOAT,f2_Dims,f2_Rank,capi_f2_intent,f2_capi);
  if (capi_f2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 2nd argument `f2' of add.m_util.tensornorm to C/Fortran array" );
  } else {
    f2 = (float *)(capi_f2_tmp->data);

  /* Processing variable i2 */
  i2_Dims[0]=3;
  capi_i2_intent |= F2PY_INTENT_IN;
  capi_i2_tmp = array_from_pyobj(PyArray_INT,i2_Dims,i2_Rank,capi_i2_intent,i2_capi);
  if (capi_i2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 4th argument `i2' of add.m_util.tensornorm to C/Fortran array" );
  } else {
    i2 = (int *)(capi_i2_tmp->data);

  /* Processing variable i1 */
  i1_Dims[0]=3;
  capi_i1_intent |= F2PY_INTENT_IN;
  capi_i1_tmp = array_from_pyobj(PyArray_INT,i1_Dims,i1_Rank,capi_i1_intent,i1_capi);
  if (capi_i1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 3rd argument `i1' of add.m_util.tensornorm to C/Fortran array" );
  } else {
    i1 = (int *)(capi_i1_tmp->data);

  /* Processing variable s */
  ;
  capi_s_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_s_tmp = array_from_pyobj(PyArray_FLOAT,s_Dims,s_Rank,capi_s_intent,Py_None);
  if (capi_s_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting hidden `s' of add.m_util.tensornorm to C/Fortran array" );
  } else {
    s = (float *)(capi_s_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(s,f1,f2,i1,i2);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_s_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_s_tmp == NULL) ... else of s*/
  /* End of cleaning variable s */
  if((PyObject *)capi_i1_tmp!=i1_capi) {
    Py_XDECREF(capi_i1_tmp); }
  }  /*if (capi_i1_tmp == NULL) ... else of i1*/
  /* End of cleaning variable i1 */
  if((PyObject *)capi_i2_tmp!=i2_capi) {
    Py_XDECREF(capi_i2_tmp); }
  }  /*if (capi_i2_tmp == NULL) ... else of i2*/
  /* End of cleaning variable i2 */
  if((PyObject *)capi_f2_tmp!=f2_capi) {
    Py_XDECREF(capi_f2_tmp); }
  }  /*if (capi_f2_tmp == NULL) ... else of f2*/
  /* End of cleaning variable f2 */
  if((PyObject *)capi_f1_tmp!=f1_capi) {
    Py_XDECREF(capi_f1_tmp); }
  }  /*if (capi_f1_tmp == NULL) ... else of f1*/
  /* End of cleaning variable f1 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of tensornorm *****************************/

/******************************* scalarsethalo *******************************/
static char doc_f2py_rout_add_m_util_scalarsethalo[] = "\
Function signature:\n\
  scalarsethalo(f,r,i1,i2)\n\
Required arguments:\n"
"  f : in/output rank-3 array('f') with bounds (:,:,:)\n"
"  r : input float\n"
"  i1 : input rank-1 array('i') with bounds (3)\n"
"  i2 : input rank-1 array('i') with bounds (3)";
/*  */
static PyObject *f2py_rout_add_m_util_scalarsethalo(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float *f = NULL;
  npy_intp f_Dims[3] = {-1, -1, -1};
  const int f_Rank = 3;
  PyArrayObject *capi_f_tmp = NULL;
  int capi_f_intent = 0;
  PyObject *f_capi = Py_None;
  float r = 0;
  PyObject *r_capi = Py_None;
  int *i1 = NULL;
  npy_intp i1_Dims[1] = {-1};
  const int i1_Rank = 1;
  PyArrayObject *capi_i1_tmp = NULL;
  int capi_i1_intent = 0;
  PyObject *i1_capi = Py_None;
  int *i2 = NULL;
  npy_intp i2_Dims[1] = {-1};
  const int i2_Rank = 1;
  PyArrayObject *capi_i2_tmp = NULL;
  int capi_i2_intent = 0;
  PyObject *i2_capi = Py_None;
  static char *capi_kwlist[] = {"f","r","i1","i2",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO|:add.m_util.scalarsethalo",\
    capi_kwlist,&f_capi,&r_capi,&i1_capi,&i2_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable r */
    f2py_success = float_from_pyobj(&r,r_capi,"add.m_util.scalarsethalo() 2nd argument (r) can't be converted to float");
  if (f2py_success) {
  /* Processing variable f */
  ;
  capi_f_intent |= F2PY_INTENT_INOUT;
  capi_f_tmp = array_from_pyobj(PyArray_FLOAT,f_Dims,f_Rank,capi_f_intent,f_capi);
  if (capi_f_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 1st argument `f' of add.m_util.scalarsethalo to C/Fortran array" );
  } else {
    f = (float *)(capi_f_tmp->data);

  /* Processing variable i1 */
  i1_Dims[0]=3;
  capi_i1_intent |= F2PY_INTENT_IN;
  capi_i1_tmp = array_from_pyobj(PyArray_INT,i1_Dims,i1_Rank,capi_i1_intent,i1_capi);
  if (capi_i1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 3rd argument `i1' of add.m_util.scalarsethalo to C/Fortran array" );
  } else {
    i1 = (int *)(capi_i1_tmp->data);

  /* Processing variable i2 */
  i2_Dims[0]=3;
  capi_i2_intent |= F2PY_INTENT_IN;
  capi_i2_tmp = array_from_pyobj(PyArray_INT,i2_Dims,i2_Rank,capi_i2_intent,i2_capi);
  if (capi_i2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 4th argument `i2' of add.m_util.scalarsethalo to C/Fortran array" );
  } else {
    i2 = (int *)(capi_i2_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(f,&r,i1,i2);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_i2_tmp!=i2_capi) {
    Py_XDECREF(capi_i2_tmp); }
  }  /*if (capi_i2_tmp == NULL) ... else of i2*/
  /* End of cleaning variable i2 */
  if((PyObject *)capi_i1_tmp!=i1_capi) {
    Py_XDECREF(capi_i1_tmp); }
  }  /*if (capi_i1_tmp == NULL) ... else of i1*/
  /* End of cleaning variable i1 */
  if((PyObject *)capi_f_tmp!=f_capi) {
    Py_XDECREF(capi_f_tmp); }
  }  /*if (capi_f_tmp == NULL) ... else of f*/
  /* End of cleaning variable f */
  } /*if (f2py_success) of r*/
  /* End of cleaning variable r */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of scalarsethalo ****************************/

/******************************* vectorsethalo *******************************/
static char doc_f2py_rout_add_m_util_vectorsethalo[] = "\
Function signature:\n\
  vectorsethalo(f,r,i1,i2)\n\
Required arguments:\n"
"  f : in/output rank-4 array('f') with bounds (:,:,:,:)\n"
"  r : input float\n"
"  i1 : input rank-1 array('i') with bounds (3)\n"
"  i2 : input rank-1 array('i') with bounds (3)";
/*  */
static PyObject *f2py_rout_add_m_util_vectorsethalo(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float *f = NULL;
  npy_intp f_Dims[4] = {-1, -1, -1, -1};
  const int f_Rank = 4;
  PyArrayObject *capi_f_tmp = NULL;
  int capi_f_intent = 0;
  PyObject *f_capi = Py_None;
  float r = 0;
  PyObject *r_capi = Py_None;
  int *i1 = NULL;
  npy_intp i1_Dims[1] = {-1};
  const int i1_Rank = 1;
  PyArrayObject *capi_i1_tmp = NULL;
  int capi_i1_intent = 0;
  PyObject *i1_capi = Py_None;
  int *i2 = NULL;
  npy_intp i2_Dims[1] = {-1};
  const int i2_Rank = 1;
  PyArrayObject *capi_i2_tmp = NULL;
  int capi_i2_intent = 0;
  PyObject *i2_capi = Py_None;
  static char *capi_kwlist[] = {"f","r","i1","i2",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO|:add.m_util.vectorsethalo",\
    capi_kwlist,&f_capi,&r_capi,&i1_capi,&i2_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable r */
    f2py_success = float_from_pyobj(&r,r_capi,"add.m_util.vectorsethalo() 2nd argument (r) can't be converted to float");
  if (f2py_success) {
  /* Processing variable f */
  ;
  capi_f_intent |= F2PY_INTENT_INOUT;
  capi_f_tmp = array_from_pyobj(PyArray_FLOAT,f_Dims,f_Rank,capi_f_intent,f_capi);
  if (capi_f_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 1st argument `f' of add.m_util.vectorsethalo to C/Fortran array" );
  } else {
    f = (float *)(capi_f_tmp->data);

  /* Processing variable i1 */
  i1_Dims[0]=3;
  capi_i1_intent |= F2PY_INTENT_IN;
  capi_i1_tmp = array_from_pyobj(PyArray_INT,i1_Dims,i1_Rank,capi_i1_intent,i1_capi);
  if (capi_i1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 3rd argument `i1' of add.m_util.vectorsethalo to C/Fortran array" );
  } else {
    i1 = (int *)(capi_i1_tmp->data);

  /* Processing variable i2 */
  i2_Dims[0]=3;
  capi_i2_intent |= F2PY_INTENT_IN;
  capi_i2_tmp = array_from_pyobj(PyArray_INT,i2_Dims,i2_Rank,capi_i2_intent,i2_capi);
  if (capi_i2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(add_error,"failed in converting 4th argument `i2' of add.m_util.vectorsethalo to C/Fortran array" );
  } else {
    i2 = (int *)(capi_i2_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(f,&r,i1,i2);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_i2_tmp!=i2_capi) {
    Py_XDECREF(capi_i2_tmp); }
  }  /*if (capi_i2_tmp == NULL) ... else of i2*/
  /* End of cleaning variable i2 */
  if((PyObject *)capi_i1_tmp!=i1_capi) {
    Py_XDECREF(capi_i1_tmp); }
  }  /*if (capi_i1_tmp == NULL) ... else of i1*/
  /* End of cleaning variable i1 */
  if((PyObject *)capi_f_tmp!=f_capi) {
    Py_XDECREF(capi_f_tmp); }
  }  /*if (capi_f_tmp == NULL) ... else of f*/
  /* End of cleaning variable f */
  } /*if (f2py_success) of r*/
  /* End of cleaning variable r */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of vectorsethalo ****************************/

/*********************************** timer ***********************************/
static char doc_f2py_rout_add_m_util_timer[] = "\
Function signature:\n\
  timer = timer(i)\n\
Required arguments:\n"
"  i : input int\n"
"Return objects:\n"
"  timer : float";
/* #declfortranroutine# */
static PyObject *f2py_rout_add_m_util_timer(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float timer = 0;
  int i = 0;
  PyObject *i_capi = Py_None;
  static char *capi_kwlist[] = {"i",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O|:add.m_util.timer",\
    capi_kwlist,&i_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable i */
    f2py_success = int_from_pyobj(&i,i_capi,"add.m_util.timer() 1st argument (i) can't be converted to int");
  if (f2py_success) {
  /* Processing variable timer */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&timer,&i);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("f",timer);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable timer */
  } /*if (f2py_success) of i*/
  /* End of cleaning variable i */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of timer ********************************/

/*********************************** strtok ***********************************/
static char doc_f2py_rout_add_m_util_strtok[] = "\
Function signature:\n\
  tok = strtok(str)\n\
Required arguments:\n"
"  str : in/output rank-0 array(string(len=-1),'c')\n"
"Return objects:\n"
"  tok : string(len=-1)";
/*  */
static PyObject *f2py_rout_add_m_util_strtok(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,string,size_t,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  string str = NULL;
  int slen(str);
  PyObject *str_capi = Py_None;
  string tok = NULL;
  int slen(tok);
  PyObject *tok_capi = Py_None;
  static char *capi_kwlist[] = {"str",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O|:add.m_util.strtok",\
    capi_kwlist,&str_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable tok */
  slen(tok) = -1;
  f2py_success = string_from_pyobj(&tok,&slen(tok),"",tok_capi,"string_from_pyobj failed in converting hidden `tok' of add.m_util.strtok to C string");
  if (f2py_success) {
  /* Processing variable str */
  slen(str) = -1;
  f2py_success = string_from_pyobj(&str,&slen(str),"",str_capi,"string_from_pyobj failed in converting 1st argument `str' of add.m_util.strtok to C string");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(str,tok,slen(str),slen(tok));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
  f2py_success = try_pyarr_from_string(str_capi,str);
  if (f2py_success) {
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("z",tok);
/*closepyobjfrom*/
  } /*if (f2py_success) of str pyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    STRINGFREE(str);
  }  /*if (f2py_success) of str*/
  /* End of cleaning variable str */
    STRINGFREE(tok);
  }  /*if (f2py_success) of tok*/
  /* End of cleaning variable tok */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of strtok *******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_m_util_def[] = {
  {"zone",-1,{{-1}},0,NULL,(void *)f2py_rout_add_m_util_zone,doc_f2py_rout_add_m_util_zone},
  {"cube",-1,{{-1}},0,NULL,(void *)f2py_rout_add_m_util_cube,doc_f2py_rout_add_m_util_cube},
  {"invert",-1,{{-1}},0,NULL,(void *)f2py_rout_add_m_util_invert,doc_f2py_rout_add_m_util_invert},
  {"scalaraverage",-1,{{-1}},0,NULL,(void *)f2py_rout_add_m_util_scalaraverage,doc_f2py_rout_add_m_util_scalaraverage},
  {"vectoraverage",-1,{{-1}},0,NULL,(void *)f2py_rout_add_m_util_vectoraverage,doc_f2py_rout_add_m_util_vectoraverage},
  {"radius",-1,{{-1}},0,NULL,(void *)f2py_rout_add_m_util_radius,doc_f2py_rout_add_m_util_radius},
  {"vectornorm",-1,{{-1}},0,NULL,(void *)f2py_rout_add_m_util_vectornorm,doc_f2py_rout_add_m_util_vectornorm},
  {"tensornorm",-1,{{-1}},0,NULL,(void *)f2py_rout_add_m_util_tensornorm,doc_f2py_rout_add_m_util_tensornorm},
  {"scalarsethalo",-1,{{-1}},0,NULL,(void *)f2py_rout_add_m_util_scalarsethalo,doc_f2py_rout_add_m_util_scalarsethalo},
  {"vectorsethalo",-1,{{-1}},0,NULL,(void *)f2py_rout_add_m_util_vectorsethalo,doc_f2py_rout_add_m_util_vectorsethalo},
  {"timer",-1,{{-1}},0,NULL,(void *)f2py_rout_add_m_util_timer,doc_f2py_rout_add_m_util_timer},
  {"strtok",-1,{{-1}},0,NULL,(void *)f2py_rout_add_m_util_strtok,doc_f2py_rout_add_m_util_strtok},
  {NULL}
};

static void f2py_setup_m_util(char *zone,char *cube,char *invert,char *scalaraverage,char *vectoraverage,char *radius,char *vectornorm,char *tensornorm,char *scalarsethalo,char *vectorsethalo,char *timer,char *strtok) {
  int i_f2py=0;
  f2py_m_util_def[i_f2py++].data = zone;
  f2py_m_util_def[i_f2py++].data = cube;
  f2py_m_util_def[i_f2py++].data = invert;
  f2py_m_util_def[i_f2py++].data = scalaraverage;
  f2py_m_util_def[i_f2py++].data = vectoraverage;
  f2py_m_util_def[i_f2py++].data = radius;
  f2py_m_util_def[i_f2py++].data = vectornorm;
  f2py_m_util_def[i_f2py++].data = tensornorm;
  f2py_m_util_def[i_f2py++].data = scalarsethalo;
  f2py_m_util_def[i_f2py++].data = vectorsethalo;
  f2py_m_util_def[i_f2py++].data = timer;
  f2py_m_util_def[i_f2py++].data = strtok;
}
extern void F_FUNC_US(f2pyinitm_util,F2PYINITM_UTIL)(void (*)(char *,char *,char *,char *,char *,char *,char *,char *,char *,char *,char *,char *));
static void f2py_init_m_util(void) {
  F_FUNC_US(f2pyinitm_util,F2PYINITM_UTIL)(f2py_setup_m_util);
}

/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

PyMODINIT_FUNC initadd(void) {
  int i;
  PyObject *m,*d, *s;
  m = add_module = Py_InitModule("add", f2py_module_methods);
  PyFortran_Type.ob_type = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module add (failed to import numpy)"); return;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
  s = PyString_FromString("This module 'add' is auto-generated with f2py (version:2_4954).\nFunctions:\n"
"Fortran 90/95 modules:\n""  m_util --- zone(),cube(),invert(),scalaraverage(),vectoraverage(),radius(),vectornorm(),tensornorm(),scalarsethalo(),vectorsethalo(),timer(),strtok()"".");
  PyDict_SetItemString(d, "__doc__", s);
  add_error = PyErr_NewException ("add.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));












/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "m_util", PyFortranObject_New(f2py_m_util_def,f2py_init_m_util));
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"add");
#endif

}
#ifdef __cplusplus
}
#endif
