% Isosurface viz

hisosurf = [];
if ~fscl, return, end
isoval = isofrac * fscl;
if comp, isoval = isoval * [ -1 1 ]; end
if cellfocus
  n = i2 - i1 + 1;
  l = 1:n(3);
  k = 1:n(2);
  j = 1:n(1);
  xg = 0.125 * ( ...
    xg(j,k,l,:) + xg(j+1,k+1,l+1,:) + ...
    xg(j+1,k,l,:) + xg(j,k+1,l+1,:) + ...
    xg(j,k+1,l,:) + xg(j+1,k,l+1,:) + ...
    xg(j,k,l+1,:) + xg(j+1,k+1,l,:) );
else
  xg = x;
end
vg = permute( vg, [2 1 3] );
xg = permute( xg, [2 1 3 4] );
for i = 1:length( isoval );
  ival = abs( isoval(i) );
  tmp = isosurface( xg(:,:,:,1), xg(:,:,:,2), xg(:,:,:,3), ...
    sign( isoval(i) ) * v(ic), ival );
  if ~isempty( tmp.vertices )
    hisosurf(end+1) = patch( tmp, ...
      'CData', isoval(i), ...
      'Tag', 'isosurf', ...
      'EdgeColor', 'none', ...
      'FaceColor', 'flat', ...
      'AmbientStrength',  .6, ...
      'DiffuseStrength',  .6, ...
      'SpecularStrength', .9, ...
      'SpecularExponent', 10, ...
      'FaceLighting', 'phong', ...
      'BackFaceLighting', 'lit' );
  end
end

