% Figure window

function tsfigure( colorscheme )

if colorscheme, foreground = [ 1 1 1 ]; background = [ 0 0 0 ];
else            foreground = [ 0 0 0 ]; background = [ 1 1 1 ];
end

figure

set( gcf, ...
  'Name', [ 'Time Series ' num2str(gcf) ], ...
  'NumberTitle', 'off', ...
  'KeyPressFcn', 'delete(gcbf)', ...
  'Color', background, ...
  'DefaultAxesColorOrder', foreground, ...
  'DefaultAxesColor', background, ...
  'DefaultAxesXColor', foreground, ...
  'DefaultAxesYColor', foreground, ...
  'DefaultAxesZColor', foreground, ...
  'DefaultLineColor', foreground, ...
  'DefaultLineLinewidth', 2, ...
  'DefaultTextHorizontalAlignment', 'center', ...
  'DefaultTextColor', foreground )

