% Figure window

function tsfigure( dark )

if ~exist( 'dark', 'var' ), dark = 1;
end

if dark, foreground = [ 1 1 1 ]; background = [ 0 0 0 ]; linewidth = 1;
else     foreground = [ 0 0 0 ]; background = [ 1 1 1 ]; linewidth = 1;
end

figure

set( gcf, ...
  'Name', [ 'Time Series ' num2str(gcf) ], ...
  'NumberTitle', 'off', ...
  'KeyPressFcn', 'delete(gcbf)', ...
  'Color', background, ...
  'DefaultAxesColorOrder', foreground, ...
  'DefaultAxesColor', background, ...
  'DefaultAxesXColor', foreground, ...
  'DefaultAxesYColor', foreground, ...
  'DefaultAxesZColor', foreground, ...
  'DefaultLineColor', foreground, ...
  'DefaultLineLinewidth', linewidth, ...
  'DefaultTextHorizontalAlignment', 'center', ...
  'DefaultTextColor', foreground )

