#!/bin/bash -e

rundir=$( pwd )

cd ../..

tar zcvf sord/sord.tgz \
  sord/readme \
  sord/fortran/*.f95 \
  sord/fortran/sord \
  sord/fortran/tarball \
  sord/fortran/in \
  sord/fortran/defaults \
  sord/matlab/*.m \
  sord/matlab/sord \
  sord/matlab/tarball \
  sord/matlab/batchjob

cd sord

tag=$( date +%Y-%m-%d-%H-%M-%S )

cp sord.tgz "save/sord-$tag.tgz"

